// Code generated by ent, DO NOT EDIT.

package outboxevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the outboxevent type in the database.
	Label = "outbox_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTopic holds the string denoting the topic field in the database.
	FieldTopic = "topic"
	// FieldAggregateID holds the string denoting the aggregate_id field in the database.
	FieldAggregateID = "aggregate_id"
	// FieldAggregateKey holds the string denoting the aggregate_key field in the database.
	FieldAggregateKey = "aggregate_key"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the outboxevent in the database.
	Table = "outbox_events"
)

// Columns holds all SQL columns for outboxevent fields.
var Columns = []string{
	FieldID,
	FieldTopic,
	FieldAggregateID,
	FieldAggregateKey,
	FieldPayload,
	FieldPublishedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the OutboxEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTopic orders the results by the topic field.
func ByTopic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopic, opts...).ToFunc()
}

// ByAggregateID orders the results by the aggregate_id field.
func ByAggregateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregateID, opts...).ToFunc()
}

// ByAggregateKey orders the results by the aggregate_key field.
func ByAggregateKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregateKey, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
