// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/fulfillmentattempt"
)

// FulfillmentAttempt is the model entity for the FulfillmentAttempt schema.
type FulfillmentAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID string `json:"job_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FulfillmentAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fulfillmentattempt.FieldID, fulfillmentattempt.FieldJobID, fulfillmentattempt.FieldStatus, fulfillmentattempt.FieldError:
			values[i] = new(sql.NullString)
		case fulfillmentattempt.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FulfillmentAttempt fields.
func (_m *FulfillmentAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fulfillmentattempt.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case fulfillmentattempt.FieldJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.String
			}
		case fulfillmentattempt.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case fulfillmentattempt.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case fulfillmentattempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FulfillmentAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *FulfillmentAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FulfillmentAttempt.
// Note that you need to call FulfillmentAttempt.Unwrap() before calling this method if this FulfillmentAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FulfillmentAttempt) Update() *FulfillmentAttemptUpdateOne {
	return NewFulfillmentAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FulfillmentAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FulfillmentAttempt) Unwrap() *FulfillmentAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FulfillmentAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FulfillmentAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("FulfillmentAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_id=")
	builder.WriteString(_m.JobID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FulfillmentAttempts is a parsable slice of FulfillmentAttempt.
type FulfillmentAttempts []*FulfillmentAttempt
