// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/node"
	"github.com/rayip/rayip/services/api/ent/predicate"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *NodeUpdate) SetCode(v string) *NodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableCode(v *string) *NodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeUpdate) SetStatus(v string) *NodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableStatus(v *string) *NodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBundleVersion sets the "bundle_version" field.
func (_u *NodeUpdate) SetBundleVersion(v string) *NodeUpdate {
	_u.mutation.SetBundleVersion(v)
	return _u
}

// SetNillableBundleVersion sets the "bundle_version" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableBundleVersion(v *string) *NodeUpdate {
	if v != nil {
		_u.SetBundleVersion(*v)
	}
	return _u
}

// SetAgentVersion sets the "agent_version" field.
func (_u *NodeUpdate) SetAgentVersion(v string) *NodeUpdate {
	_u.mutation.SetAgentVersion(v)
	return _u
}

// SetNillableAgentVersion sets the "agent_version" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableAgentVersion(v *string) *NodeUpdate {
	if v != nil {
		_u.SetAgentVersion(*v)
	}
	return _u
}

// SetXrayVersion sets the "xray_version" field.
func (_u *NodeUpdate) SetXrayVersion(v string) *NodeUpdate {
	_u.mutation.SetXrayVersion(v)
	return _u
}

// SetNillableXrayVersion sets the "xray_version" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableXrayVersion(v *string) *NodeUpdate {
	if v != nil {
		_u.SetXrayVersion(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *NodeUpdate) SetCapabilities(v []string) *NodeUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *NodeUpdate) AppendCapabilities(v []string) *NodeUpdate {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// SetPublicIP sets the "public_ip" field.
func (_u *NodeUpdate) SetPublicIP(v string) *NodeUpdate {
	_u.mutation.SetPublicIP(v)
	return _u
}

// SetNillablePublicIP sets the "public_ip" field if the given value is not nil.
func (_u *NodeUpdate) SetNillablePublicIP(v *string) *NodeUpdate {
	if v != nil {
		_u.SetPublicIP(*v)
	}
	return _u
}

// SetCandidatePublicIps sets the "candidate_public_ips" field.
func (_u *NodeUpdate) SetCandidatePublicIps(v []string) *NodeUpdate {
	_u.mutation.SetCandidatePublicIps(v)
	return _u
}

// AppendCandidatePublicIps appends value to the "candidate_public_ips" field.
func (_u *NodeUpdate) AppendCandidatePublicIps(v []string) *NodeUpdate {
	_u.mutation.AppendCandidatePublicIps(v)
	return _u
}

// SetScanHost sets the "scan_host" field.
func (_u *NodeUpdate) SetScanHost(v string) *NodeUpdate {
	_u.mutation.SetScanHost(v)
	return _u
}

// SetNillableScanHost sets the "scan_host" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableScanHost(v *string) *NodeUpdate {
	if v != nil {
		_u.SetScanHost(*v)
	}
	return _u
}

// SetProbePort sets the "probe_port" field.
func (_u *NodeUpdate) SetProbePort(v uint32) *NodeUpdate {
	_u.mutation.ResetProbePort()
	_u.mutation.SetProbePort(v)
	return _u
}

// SetNillableProbePort sets the "probe_port" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableProbePort(v *uint32) *NodeUpdate {
	if v != nil {
		_u.SetProbePort(*v)
	}
	return _u
}

// AddProbePort adds value to the "probe_port" field.
func (_u *NodeUpdate) AddProbePort(v int32) *NodeUpdate {
	_u.mutation.AddProbePort(v)
	return _u
}

// SetProbeProtocols sets the "probe_protocols" field.
func (_u *NodeUpdate) SetProbeProtocols(v []string) *NodeUpdate {
	_u.mutation.SetProbeProtocols(v)
	return _u
}

// AppendProbeProtocols appends value to the "probe_protocols" field.
func (_u *NodeUpdate) AppendProbeProtocols(v []string) *NodeUpdate {
	_u.mutation.AppendProbeProtocols(v)
	return _u
}

// SetProbeCheckedAt sets the "probe_checked_at" field.
func (_u *NodeUpdate) SetProbeCheckedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetProbeCheckedAt(v)
	return _u
}

// SetNillableProbeCheckedAt sets the "probe_checked_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableProbeCheckedAt(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetProbeCheckedAt(*v)
	}
	return _u
}

// ClearProbeCheckedAt clears the value of the "probe_checked_at" field.
func (_u *NodeUpdate) ClearProbeCheckedAt() *NodeUpdate {
	_u.mutation.ClearProbeCheckedAt()
	return _u
}

// SetLastScanStatus sets the "last_scan_status" field.
func (_u *NodeUpdate) SetLastScanStatus(v string) *NodeUpdate {
	_u.mutation.SetLastScanStatus(v)
	return _u
}

// SetNillableLastScanStatus sets the "last_scan_status" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastScanStatus(v *string) *NodeUpdate {
	if v != nil {
		_u.SetLastScanStatus(*v)
	}
	return _u
}

// SetLastScanError sets the "last_scan_error" field.
func (_u *NodeUpdate) SetLastScanError(v string) *NodeUpdate {
	_u.mutation.SetLastScanError(v)
	return _u
}

// SetNillableLastScanError sets the "last_scan_error" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastScanError(v *string) *NodeUpdate {
	if v != nil {
		_u.SetLastScanError(*v)
	}
	return _u
}

// SetLastScanReasonCode sets the "last_scan_reason_code" field.
func (_u *NodeUpdate) SetLastScanReasonCode(v string) *NodeUpdate {
	_u.mutation.SetLastScanReasonCode(v)
	return _u
}

// SetNillableLastScanReasonCode sets the "last_scan_reason_code" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastScanReasonCode(v *string) *NodeUpdate {
	if v != nil {
		_u.SetLastScanReasonCode(*v)
	}
	return _u
}

// SetLastScanLatencyMs sets the "last_scan_latency_ms" field.
func (_u *NodeUpdate) SetLastScanLatencyMs(v int64) *NodeUpdate {
	_u.mutation.ResetLastScanLatencyMs()
	_u.mutation.SetLastScanLatencyMs(v)
	return _u
}

// SetNillableLastScanLatencyMs sets the "last_scan_latency_ms" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastScanLatencyMs(v *int64) *NodeUpdate {
	if v != nil {
		_u.SetLastScanLatencyMs(*v)
	}
	return _u
}

// AddLastScanLatencyMs adds value to the "last_scan_latency_ms" field.
func (_u *NodeUpdate) AddLastScanLatencyMs(v int64) *NodeUpdate {
	_u.mutation.AddLastScanLatencyMs(v)
	return _u
}

// SetLastScanAt sets the "last_scan_at" field.
func (_u *NodeUpdate) SetLastScanAt(v time.Time) *NodeUpdate {
	_u.mutation.SetLastScanAt(v)
	return _u
}

// SetNillableLastScanAt sets the "last_scan_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastScanAt(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetLastScanAt(*v)
	}
	return _u
}

// ClearLastScanAt clears the value of the "last_scan_at" field.
func (_u *NodeUpdate) ClearLastScanAt() *NodeUpdate {
	_u.mutation.ClearLastScanAt()
	return _u
}

// SetLastOnlineAt sets the "last_online_at" field.
func (_u *NodeUpdate) SetLastOnlineAt(v time.Time) *NodeUpdate {
	_u.mutation.SetLastOnlineAt(v)
	return _u
}

// SetNillableLastOnlineAt sets the "last_online_at" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastOnlineAt(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetLastOnlineAt(*v)
	}
	return _u
}

// ClearLastOnlineAt clears the value of the "last_online_at" field.
func (_u *NodeUpdate) ClearLastOnlineAt() *NodeUpdate {
	_u.mutation.ClearLastOnlineAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdate) SetUpdatedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(node.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(node.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BundleVersion(); ok {
		_spec.SetField(node.FieldBundleVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentVersion(); ok {
		_spec.SetField(node.FieldAgentVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.XrayVersion(); ok {
		_spec.SetField(node.FieldXrayVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(node.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldCapabilities, value)
		})
	}
	if value, ok := _u.mutation.PublicIP(); ok {
		_spec.SetField(node.FieldPublicIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.CandidatePublicIps(); ok {
		_spec.SetField(node.FieldCandidatePublicIps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCandidatePublicIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldCandidatePublicIps, value)
		})
	}
	if value, ok := _u.mutation.ScanHost(); ok {
		_spec.SetField(node.FieldScanHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbePort(); ok {
		_spec.SetField(node.FieldProbePort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedProbePort(); ok {
		_spec.AddField(node.FieldProbePort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.ProbeProtocols(); ok {
		_spec.SetField(node.FieldProbeProtocols, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProbeProtocols(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldProbeProtocols, value)
		})
	}
	if value, ok := _u.mutation.ProbeCheckedAt(); ok {
		_spec.SetField(node.FieldProbeCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.ProbeCheckedAtCleared() {
		_spec.ClearField(node.FieldProbeCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastScanStatus(); ok {
		_spec.SetField(node.FieldLastScanStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastScanError(); ok {
		_spec.SetField(node.FieldLastScanError, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastScanReasonCode(); ok {
		_spec.SetField(node.FieldLastScanReasonCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastScanLatencyMs(); ok {
		_spec.SetField(node.FieldLastScanLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastScanLatencyMs(); ok {
		_spec.AddField(node.FieldLastScanLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastScanAt(); ok {
		_spec.SetField(node.FieldLastScanAt, field.TypeTime, value)
	}
	if _u.mutation.LastScanAtCleared() {
		_spec.ClearField(node.FieldLastScanAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastOnlineAt(); ok {
		_spec.SetField(node.FieldLastOnlineAt, field.TypeTime, value)
	}
	if _u.mutation.LastOnlineAtCleared() {
		_spec.ClearField(node.FieldLastOnlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetCode sets the "code" field.
func (_u *NodeUpdateOne) SetCode(v string) *NodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableCode(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NodeUpdateOne) SetStatus(v string) *NodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableStatus(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBundleVersion sets the "bundle_version" field.
func (_u *NodeUpdateOne) SetBundleVersion(v string) *NodeUpdateOne {
	_u.mutation.SetBundleVersion(v)
	return _u
}

// SetNillableBundleVersion sets the "bundle_version" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableBundleVersion(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetBundleVersion(*v)
	}
	return _u
}

// SetAgentVersion sets the "agent_version" field.
func (_u *NodeUpdateOne) SetAgentVersion(v string) *NodeUpdateOne {
	_u.mutation.SetAgentVersion(v)
	return _u
}

// SetNillableAgentVersion sets the "agent_version" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableAgentVersion(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetAgentVersion(*v)
	}
	return _u
}

// SetXrayVersion sets the "xray_version" field.
func (_u *NodeUpdateOne) SetXrayVersion(v string) *NodeUpdateOne {
	_u.mutation.SetXrayVersion(v)
	return _u
}

// SetNillableXrayVersion sets the "xray_version" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableXrayVersion(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetXrayVersion(*v)
	}
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *NodeUpdateOne) SetCapabilities(v []string) *NodeUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *NodeUpdateOne) AppendCapabilities(v []string) *NodeUpdateOne {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// SetPublicIP sets the "public_ip" field.
func (_u *NodeUpdateOne) SetPublicIP(v string) *NodeUpdateOne {
	_u.mutation.SetPublicIP(v)
	return _u
}

// SetNillablePublicIP sets the "public_ip" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePublicIP(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetPublicIP(*v)
	}
	return _u
}

// SetCandidatePublicIps sets the "candidate_public_ips" field.
func (_u *NodeUpdateOne) SetCandidatePublicIps(v []string) *NodeUpdateOne {
	_u.mutation.SetCandidatePublicIps(v)
	return _u
}

// AppendCandidatePublicIps appends value to the "candidate_public_ips" field.
func (_u *NodeUpdateOne) AppendCandidatePublicIps(v []string) *NodeUpdateOne {
	_u.mutation.AppendCandidatePublicIps(v)
	return _u
}

// SetScanHost sets the "scan_host" field.
func (_u *NodeUpdateOne) SetScanHost(v string) *NodeUpdateOne {
	_u.mutation.SetScanHost(v)
	return _u
}

// SetNillableScanHost sets the "scan_host" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableScanHost(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetScanHost(*v)
	}
	return _u
}

// SetProbePort sets the "probe_port" field.
func (_u *NodeUpdateOne) SetProbePort(v uint32) *NodeUpdateOne {
	_u.mutation.ResetProbePort()
	_u.mutation.SetProbePort(v)
	return _u
}

// SetNillableProbePort sets the "probe_port" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableProbePort(v *uint32) *NodeUpdateOne {
	if v != nil {
		_u.SetProbePort(*v)
	}
	return _u
}

// AddProbePort adds value to the "probe_port" field.
func (_u *NodeUpdateOne) AddProbePort(v int32) *NodeUpdateOne {
	_u.mutation.AddProbePort(v)
	return _u
}

// SetProbeProtocols sets the "probe_protocols" field.
func (_u *NodeUpdateOne) SetProbeProtocols(v []string) *NodeUpdateOne {
	_u.mutation.SetProbeProtocols(v)
	return _u
}

// AppendProbeProtocols appends value to the "probe_protocols" field.
func (_u *NodeUpdateOne) AppendProbeProtocols(v []string) *NodeUpdateOne {
	_u.mutation.AppendProbeProtocols(v)
	return _u
}

// SetProbeCheckedAt sets the "probe_checked_at" field.
func (_u *NodeUpdateOne) SetProbeCheckedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetProbeCheckedAt(v)
	return _u
}

// SetNillableProbeCheckedAt sets the "probe_checked_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableProbeCheckedAt(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetProbeCheckedAt(*v)
	}
	return _u
}

// ClearProbeCheckedAt clears the value of the "probe_checked_at" field.
func (_u *NodeUpdateOne) ClearProbeCheckedAt() *NodeUpdateOne {
	_u.mutation.ClearProbeCheckedAt()
	return _u
}

// SetLastScanStatus sets the "last_scan_status" field.
func (_u *NodeUpdateOne) SetLastScanStatus(v string) *NodeUpdateOne {
	_u.mutation.SetLastScanStatus(v)
	return _u
}

// SetNillableLastScanStatus sets the "last_scan_status" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastScanStatus(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetLastScanStatus(*v)
	}
	return _u
}

// SetLastScanError sets the "last_scan_error" field.
func (_u *NodeUpdateOne) SetLastScanError(v string) *NodeUpdateOne {
	_u.mutation.SetLastScanError(v)
	return _u
}

// SetNillableLastScanError sets the "last_scan_error" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastScanError(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetLastScanError(*v)
	}
	return _u
}

// SetLastScanReasonCode sets the "last_scan_reason_code" field.
func (_u *NodeUpdateOne) SetLastScanReasonCode(v string) *NodeUpdateOne {
	_u.mutation.SetLastScanReasonCode(v)
	return _u
}

// SetNillableLastScanReasonCode sets the "last_scan_reason_code" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastScanReasonCode(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetLastScanReasonCode(*v)
	}
	return _u
}

// SetLastScanLatencyMs sets the "last_scan_latency_ms" field.
func (_u *NodeUpdateOne) SetLastScanLatencyMs(v int64) *NodeUpdateOne {
	_u.mutation.ResetLastScanLatencyMs()
	_u.mutation.SetLastScanLatencyMs(v)
	return _u
}

// SetNillableLastScanLatencyMs sets the "last_scan_latency_ms" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastScanLatencyMs(v *int64) *NodeUpdateOne {
	if v != nil {
		_u.SetLastScanLatencyMs(*v)
	}
	return _u
}

// AddLastScanLatencyMs adds value to the "last_scan_latency_ms" field.
func (_u *NodeUpdateOne) AddLastScanLatencyMs(v int64) *NodeUpdateOne {
	_u.mutation.AddLastScanLatencyMs(v)
	return _u
}

// SetLastScanAt sets the "last_scan_at" field.
func (_u *NodeUpdateOne) SetLastScanAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetLastScanAt(v)
	return _u
}

// SetNillableLastScanAt sets the "last_scan_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastScanAt(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetLastScanAt(*v)
	}
	return _u
}

// ClearLastScanAt clears the value of the "last_scan_at" field.
func (_u *NodeUpdateOne) ClearLastScanAt() *NodeUpdateOne {
	_u.mutation.ClearLastScanAt()
	return _u
}

// SetLastOnlineAt sets the "last_online_at" field.
func (_u *NodeUpdateOne) SetLastOnlineAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetLastOnlineAt(v)
	return _u
}

// SetNillableLastOnlineAt sets the "last_online_at" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastOnlineAt(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetLastOnlineAt(*v)
	}
	return _u
}

// ClearLastOnlineAt clears the value of the "last_online_at" field.
func (_u *NodeUpdateOne) ClearLastOnlineAt() *NodeUpdateOne {
	_u.mutation.ClearLastOnlineAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdateOne) SetUpdatedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(node.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(node.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BundleVersion(); ok {
		_spec.SetField(node.FieldBundleVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentVersion(); ok {
		_spec.SetField(node.FieldAgentVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.XrayVersion(); ok {
		_spec.SetField(node.FieldXrayVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(node.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldCapabilities, value)
		})
	}
	if value, ok := _u.mutation.PublicIP(); ok {
		_spec.SetField(node.FieldPublicIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.CandidatePublicIps(); ok {
		_spec.SetField(node.FieldCandidatePublicIps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCandidatePublicIps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldCandidatePublicIps, value)
		})
	}
	if value, ok := _u.mutation.ScanHost(); ok {
		_spec.SetField(node.FieldScanHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProbePort(); ok {
		_spec.SetField(node.FieldProbePort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedProbePort(); ok {
		_spec.AddField(node.FieldProbePort, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.ProbeProtocols(); ok {
		_spec.SetField(node.FieldProbeProtocols, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProbeProtocols(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, node.FieldProbeProtocols, value)
		})
	}
	if value, ok := _u.mutation.ProbeCheckedAt(); ok {
		_spec.SetField(node.FieldProbeCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.ProbeCheckedAtCleared() {
		_spec.ClearField(node.FieldProbeCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastScanStatus(); ok {
		_spec.SetField(node.FieldLastScanStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastScanError(); ok {
		_spec.SetField(node.FieldLastScanError, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastScanReasonCode(); ok {
		_spec.SetField(node.FieldLastScanReasonCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastScanLatencyMs(); ok {
		_spec.SetField(node.FieldLastScanLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastScanLatencyMs(); ok {
		_spec.AddField(node.FieldLastScanLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastScanAt(); ok {
		_spec.SetField(node.FieldLastScanAt, field.TypeTime, value)
	}
	if _u.mutation.LastScanAtCleared() {
		_spec.ClearField(node.FieldLastScanAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastOnlineAt(); ok {
		_spec.SetField(node.FieldLastOnlineAt, field.TypeTime, value)
	}
	if _u.mutation.LastOnlineAtCleared() {
		_spec.ClearField(node.FieldLastOnlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
