// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/nodeagentsession"
)

// NodeAgentSession is the model entity for the NodeAgentSession schema.
type NodeAgentSession struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// APIInstanceID holds the value of the "api_instance_id" field.
	APIInstanceID string `json:"api_instance_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// BundleVersion holds the value of the "bundle_version" field.
	BundleVersion string `json:"bundle_version,omitempty"`
	// ConnectedAt holds the value of the "connected_at" field.
	ConnectedAt time.Time `json:"connected_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NodeAgentSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case nodeagentsession.FieldID, nodeagentsession.FieldNodeID, nodeagentsession.FieldAPIInstanceID, nodeagentsession.FieldStatus, nodeagentsession.FieldBundleVersion:
			values[i] = new(sql.NullString)
		case nodeagentsession.FieldConnectedAt, nodeagentsession.FieldLastSeenAt, nodeagentsession.FieldCreatedAt, nodeagentsession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NodeAgentSession fields.
func (_m *NodeAgentSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nodeagentsession.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case nodeagentsession.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case nodeagentsession.FieldAPIInstanceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_instance_id", values[i])
			} else if value.Valid {
				_m.APIInstanceID = value.String
			}
		case nodeagentsession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case nodeagentsession.FieldBundleVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bundle_version", values[i])
			} else if value.Valid {
				_m.BundleVersion = value.String
			}
		case nodeagentsession.FieldConnectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field connected_at", values[i])
			} else if value.Valid {
				_m.ConnectedAt = value.Time
			}
		case nodeagentsession.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case nodeagentsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case nodeagentsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NodeAgentSession.
// This includes values selected through modifiers, order, etc.
func (_m *NodeAgentSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NodeAgentSession.
// Note that you need to call NodeAgentSession.Unwrap() before calling this method if this NodeAgentSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NodeAgentSession) Update() *NodeAgentSessionUpdateOne {
	return NewNodeAgentSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NodeAgentSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NodeAgentSession) Unwrap() *NodeAgentSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NodeAgentSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NodeAgentSession) String() string {
	var builder strings.Builder
	builder.WriteString("NodeAgentSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	builder.WriteString("api_instance_id=")
	builder.WriteString(_m.APIInstanceID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("bundle_version=")
	builder.WriteString(_m.BundleVersion)
	builder.WriteString(", ")
	builder.WriteString("connected_at=")
	builder.WriteString(_m.ConnectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NodeAgentSessions is a parsable slice of NodeAgentSession.
type NodeAgentSessions []*NodeAgentSession
