// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/nodejob"
)

// NodeJobCreate is the builder for creating a NodeJob entity.
type NodeJobCreate struct {
	config
	mutation *NodeJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNodeID sets the "node_id" field.
func (_c *NodeJobCreate) SetNodeID(v string) *NodeJobCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *NodeJobCreate) SetStatus(v string) *NodeJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetBaseRevision sets the "base_revision" field.
func (_c *NodeJobCreate) SetBaseRevision(v uint64) *NodeJobCreate {
	_c.mutation.SetBaseRevision(v)
	return _c
}

// SetNillableBaseRevision sets the "base_revision" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableBaseRevision(v *uint64) *NodeJobCreate {
	if v != nil {
		_c.SetBaseRevision(*v)
	}
	return _c
}

// SetTargetRevision sets the "target_revision" field.
func (_c *NodeJobCreate) SetTargetRevision(v uint64) *NodeJobCreate {
	_c.mutation.SetTargetRevision(v)
	return _c
}

// SetNillableTargetRevision sets the "target_revision" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableTargetRevision(v *uint64) *NodeJobCreate {
	if v != nil {
		_c.SetTargetRevision(*v)
	}
	return _c
}

// SetAcceptedRevision sets the "accepted_revision" field.
func (_c *NodeJobCreate) SetAcceptedRevision(v uint64) *NodeJobCreate {
	_c.mutation.SetAcceptedRevision(v)
	return _c
}

// SetNillableAcceptedRevision sets the "accepted_revision" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableAcceptedRevision(v *uint64) *NodeJobCreate {
	if v != nil {
		_c.SetAcceptedRevision(*v)
	}
	return _c
}

// SetLastGoodRevision sets the "last_good_revision" field.
func (_c *NodeJobCreate) SetLastGoodRevision(v uint64) *NodeJobCreate {
	_c.mutation.SetLastGoodRevision(v)
	return _c
}

// SetNillableLastGoodRevision sets the "last_good_revision" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableLastGoodRevision(v *uint64) *NodeJobCreate {
	if v != nil {
		_c.SetLastGoodRevision(*v)
	}
	return _c
}

// SetApplyID sets the "apply_id" field.
func (_c *NodeJobCreate) SetApplyID(v string) *NodeJobCreate {
	_c.mutation.SetApplyID(v)
	return _c
}

// SetNillableApplyID sets the "apply_id" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableApplyID(v *string) *NodeJobCreate {
	if v != nil {
		_c.SetApplyID(*v)
	}
	return _c
}

// SetVersionInfo sets the "version_info" field.
func (_c *NodeJobCreate) SetVersionInfo(v string) *NodeJobCreate {
	_c.mutation.SetVersionInfo(v)
	return _c
}

// SetNillableVersionInfo sets the "version_info" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableVersionInfo(v *string) *NodeJobCreate {
	if v != nil {
		_c.SetVersionInfo(*v)
	}
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *NodeJobCreate) SetNonce(v string) *NodeJobCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableNonce(v *string) *NodeJobCreate {
	if v != nil {
		_c.SetNonce(*v)
	}
	return _c
}

// SetErrorDetail sets the "error_detail" field.
func (_c *NodeJobCreate) SetErrorDetail(v string) *NodeJobCreate {
	_c.mutation.SetErrorDetail(v)
	return _c
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableErrorDetail(v *string) *NodeJobCreate {
	if v != nil {
		_c.SetErrorDetail(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NodeJobCreate) SetCreatedAt(v time.Time) *NodeJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableCreatedAt(v *time.Time) *NodeJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NodeJobCreate) SetUpdatedAt(v time.Time) *NodeJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NodeJobCreate) SetNillableUpdatedAt(v *time.Time) *NodeJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NodeJobCreate) SetID(v string) *NodeJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NodeJobMutation object of the builder.
func (_c *NodeJobCreate) Mutation() *NodeJobMutation {
	return _c.mutation
}

// Save creates the NodeJob in the database.
func (_c *NodeJobCreate) Save(ctx context.Context) (*NodeJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeJobCreate) SaveX(ctx context.Context) *NodeJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NodeJobCreate) defaults() {
	if _, ok := _c.mutation.BaseRevision(); !ok {
		v := nodejob.DefaultBaseRevision
		_c.mutation.SetBaseRevision(v)
	}
	if _, ok := _c.mutation.TargetRevision(); !ok {
		v := nodejob.DefaultTargetRevision
		_c.mutation.SetTargetRevision(v)
	}
	if _, ok := _c.mutation.AcceptedRevision(); !ok {
		v := nodejob.DefaultAcceptedRevision
		_c.mutation.SetAcceptedRevision(v)
	}
	if _, ok := _c.mutation.LastGoodRevision(); !ok {
		v := nodejob.DefaultLastGoodRevision
		_c.mutation.SetLastGoodRevision(v)
	}
	if _, ok := _c.mutation.ApplyID(); !ok {
		v := nodejob.DefaultApplyID
		_c.mutation.SetApplyID(v)
	}
	if _, ok := _c.mutation.VersionInfo(); !ok {
		v := nodejob.DefaultVersionInfo
		_c.mutation.SetVersionInfo(v)
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		v := nodejob.DefaultNonce
		_c.mutation.SetNonce(v)
	}
	if _, ok := _c.mutation.ErrorDetail(); !ok {
		v := nodejob.DefaultErrorDetail
		_c.mutation.SetErrorDetail(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := nodejob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := nodejob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeJobCreate) check() error {
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "NodeJob.node_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NodeJob.status"`)}
	}
	if _, ok := _c.mutation.BaseRevision(); !ok {
		return &ValidationError{Name: "base_revision", err: errors.New(`ent: missing required field "NodeJob.base_revision"`)}
	}
	if _, ok := _c.mutation.TargetRevision(); !ok {
		return &ValidationError{Name: "target_revision", err: errors.New(`ent: missing required field "NodeJob.target_revision"`)}
	}
	if _, ok := _c.mutation.AcceptedRevision(); !ok {
		return &ValidationError{Name: "accepted_revision", err: errors.New(`ent: missing required field "NodeJob.accepted_revision"`)}
	}
	if _, ok := _c.mutation.LastGoodRevision(); !ok {
		return &ValidationError{Name: "last_good_revision", err: errors.New(`ent: missing required field "NodeJob.last_good_revision"`)}
	}
	if _, ok := _c.mutation.ApplyID(); !ok {
		return &ValidationError{Name: "apply_id", err: errors.New(`ent: missing required field "NodeJob.apply_id"`)}
	}
	if _, ok := _c.mutation.VersionInfo(); !ok {
		return &ValidationError{Name: "version_info", err: errors.New(`ent: missing required field "NodeJob.version_info"`)}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "NodeJob.nonce"`)}
	}
	if _, ok := _c.mutation.ErrorDetail(); !ok {
		return &ValidationError{Name: "error_detail", err: errors.New(`ent: missing required field "NodeJob.error_detail"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NodeJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NodeJob.updated_at"`)}
	}
	return nil
}

func (_c *NodeJobCreate) sqlSave(ctx context.Context) (*NodeJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NodeJob.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeJobCreate) createSpec() (*NodeJob, *sqlgraph.CreateSpec) {
	var (
		_node = &NodeJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(nodejob.Table, sqlgraph.NewFieldSpec(nodejob.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(nodejob.FieldNodeID, field.TypeString, value)
		_node.NodeID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(nodejob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.BaseRevision(); ok {
		_spec.SetField(nodejob.FieldBaseRevision, field.TypeUint64, value)
		_node.BaseRevision = value
	}
	if value, ok := _c.mutation.TargetRevision(); ok {
		_spec.SetField(nodejob.FieldTargetRevision, field.TypeUint64, value)
		_node.TargetRevision = value
	}
	if value, ok := _c.mutation.AcceptedRevision(); ok {
		_spec.SetField(nodejob.FieldAcceptedRevision, field.TypeUint64, value)
		_node.AcceptedRevision = value
	}
	if value, ok := _c.mutation.LastGoodRevision(); ok {
		_spec.SetField(nodejob.FieldLastGoodRevision, field.TypeUint64, value)
		_node.LastGoodRevision = value
	}
	if value, ok := _c.mutation.ApplyID(); ok {
		_spec.SetField(nodejob.FieldApplyID, field.TypeString, value)
		_node.ApplyID = value
	}
	if value, ok := _c.mutation.VersionInfo(); ok {
		_spec.SetField(nodejob.FieldVersionInfo, field.TypeString, value)
		_node.VersionInfo = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(nodejob.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.ErrorDetail(); ok {
		_spec.SetField(nodejob.FieldErrorDetail, field.TypeString, value)
		_node.ErrorDetail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(nodejob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(nodejob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NodeJob.Create().
//		SetNodeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NodeJobUpsert) {
//			SetNodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *NodeJobCreate) OnConflict(opts ...sql.ConflictOption) *NodeJobUpsertOne {
	_c.conflict = opts
	return &NodeJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NodeJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NodeJobCreate) OnConflictColumns(columns ...string) *NodeJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NodeJobUpsertOne{
		create: _c,
	}
}

type (
	// NodeJobUpsertOne is the builder for "upsert"-ing
	//  one NodeJob node.
	NodeJobUpsertOne struct {
		create *NodeJobCreate
	}

	// NodeJobUpsert is the "OnConflict" setter.
	NodeJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetNodeID sets the "node_id" field.
func (u *NodeJobUpsert) SetNodeID(v string) *NodeJobUpsert {
	u.Set(nodejob.FieldNodeID, v)
	return u
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateNodeID() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldNodeID)
	return u
}

// SetStatus sets the "status" field.
func (u *NodeJobUpsert) SetStatus(v string) *NodeJobUpsert {
	u.Set(nodejob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateStatus() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldStatus)
	return u
}

// SetBaseRevision sets the "base_revision" field.
func (u *NodeJobUpsert) SetBaseRevision(v uint64) *NodeJobUpsert {
	u.Set(nodejob.FieldBaseRevision, v)
	return u
}

// UpdateBaseRevision sets the "base_revision" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateBaseRevision() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldBaseRevision)
	return u
}

// AddBaseRevision adds v to the "base_revision" field.
func (u *NodeJobUpsert) AddBaseRevision(v uint64) *NodeJobUpsert {
	u.Add(nodejob.FieldBaseRevision, v)
	return u
}

// SetTargetRevision sets the "target_revision" field.
func (u *NodeJobUpsert) SetTargetRevision(v uint64) *NodeJobUpsert {
	u.Set(nodejob.FieldTargetRevision, v)
	return u
}

// UpdateTargetRevision sets the "target_revision" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateTargetRevision() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldTargetRevision)
	return u
}

// AddTargetRevision adds v to the "target_revision" field.
func (u *NodeJobUpsert) AddTargetRevision(v uint64) *NodeJobUpsert {
	u.Add(nodejob.FieldTargetRevision, v)
	return u
}

// SetAcceptedRevision sets the "accepted_revision" field.
func (u *NodeJobUpsert) SetAcceptedRevision(v uint64) *NodeJobUpsert {
	u.Set(nodejob.FieldAcceptedRevision, v)
	return u
}

// UpdateAcceptedRevision sets the "accepted_revision" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateAcceptedRevision() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldAcceptedRevision)
	return u
}

// AddAcceptedRevision adds v to the "accepted_revision" field.
func (u *NodeJobUpsert) AddAcceptedRevision(v uint64) *NodeJobUpsert {
	u.Add(nodejob.FieldAcceptedRevision, v)
	return u
}

// SetLastGoodRevision sets the "last_good_revision" field.
func (u *NodeJobUpsert) SetLastGoodRevision(v uint64) *NodeJobUpsert {
	u.Set(nodejob.FieldLastGoodRevision, v)
	return u
}

// UpdateLastGoodRevision sets the "last_good_revision" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateLastGoodRevision() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldLastGoodRevision)
	return u
}

// AddLastGoodRevision adds v to the "last_good_revision" field.
func (u *NodeJobUpsert) AddLastGoodRevision(v uint64) *NodeJobUpsert {
	u.Add(nodejob.FieldLastGoodRevision, v)
	return u
}

// SetApplyID sets the "apply_id" field.
func (u *NodeJobUpsert) SetApplyID(v string) *NodeJobUpsert {
	u.Set(nodejob.FieldApplyID, v)
	return u
}

// UpdateApplyID sets the "apply_id" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateApplyID() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldApplyID)
	return u
}

// SetVersionInfo sets the "version_info" field.
func (u *NodeJobUpsert) SetVersionInfo(v string) *NodeJobUpsert {
	u.Set(nodejob.FieldVersionInfo, v)
	return u
}

// UpdateVersionInfo sets the "version_info" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateVersionInfo() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldVersionInfo)
	return u
}

// SetNonce sets the "nonce" field.
func (u *NodeJobUpsert) SetNonce(v string) *NodeJobUpsert {
	u.Set(nodejob.FieldNonce, v)
	return u
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateNonce() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldNonce)
	return u
}

// SetErrorDetail sets the "error_detail" field.
func (u *NodeJobUpsert) SetErrorDetail(v string) *NodeJobUpsert {
	u.Set(nodejob.FieldErrorDetail, v)
	return u
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateErrorDetail() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldErrorDetail)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NodeJobUpsert) SetUpdatedAt(v time.Time) *NodeJobUpsert {
	u.Set(nodejob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NodeJobUpsert) UpdateUpdatedAt() *NodeJobUpsert {
	u.SetExcluded(nodejob.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NodeJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(nodejob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NodeJobUpsertOne) UpdateNewValues() *NodeJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(nodejob.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(nodejob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NodeJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NodeJobUpsertOne) Ignore() *NodeJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NodeJobUpsertOne) DoNothing() *NodeJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NodeJobCreate.OnConflict
// documentation for more info.
func (u *NodeJobUpsertOne) Update(set func(*NodeJobUpsert)) *NodeJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NodeJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetNodeID sets the "node_id" field.
func (u *NodeJobUpsertOne) SetNodeID(v string) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateNodeID() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateNodeID()
	})
}

// SetStatus sets the "status" field.
func (u *NodeJobUpsertOne) SetStatus(v string) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateStatus() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateStatus()
	})
}

// SetBaseRevision sets the "base_revision" field.
func (u *NodeJobUpsertOne) SetBaseRevision(v uint64) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetBaseRevision(v)
	})
}

// AddBaseRevision adds v to the "base_revision" field.
func (u *NodeJobUpsertOne) AddBaseRevision(v uint64) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.AddBaseRevision(v)
	})
}

// UpdateBaseRevision sets the "base_revision" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateBaseRevision() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateBaseRevision()
	})
}

// SetTargetRevision sets the "target_revision" field.
func (u *NodeJobUpsertOne) SetTargetRevision(v uint64) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetTargetRevision(v)
	})
}

// AddTargetRevision adds v to the "target_revision" field.
func (u *NodeJobUpsertOne) AddTargetRevision(v uint64) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.AddTargetRevision(v)
	})
}

// UpdateTargetRevision sets the "target_revision" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateTargetRevision() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateTargetRevision()
	})
}

// SetAcceptedRevision sets the "accepted_revision" field.
func (u *NodeJobUpsertOne) SetAcceptedRevision(v uint64) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetAcceptedRevision(v)
	})
}

// AddAcceptedRevision adds v to the "accepted_revision" field.
func (u *NodeJobUpsertOne) AddAcceptedRevision(v uint64) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.AddAcceptedRevision(v)
	})
}

// UpdateAcceptedRevision sets the "accepted_revision" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateAcceptedRevision() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateAcceptedRevision()
	})
}

// SetLastGoodRevision sets the "last_good_revision" field.
func (u *NodeJobUpsertOne) SetLastGoodRevision(v uint64) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetLastGoodRevision(v)
	})
}

// AddLastGoodRevision adds v to the "last_good_revision" field.
func (u *NodeJobUpsertOne) AddLastGoodRevision(v uint64) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.AddLastGoodRevision(v)
	})
}

// UpdateLastGoodRevision sets the "last_good_revision" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateLastGoodRevision() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateLastGoodRevision()
	})
}

// SetApplyID sets the "apply_id" field.
func (u *NodeJobUpsertOne) SetApplyID(v string) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetApplyID(v)
	})
}

// UpdateApplyID sets the "apply_id" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateApplyID() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateApplyID()
	})
}

// SetVersionInfo sets the "version_info" field.
func (u *NodeJobUpsertOne) SetVersionInfo(v string) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetVersionInfo(v)
	})
}

// UpdateVersionInfo sets the "version_info" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateVersionInfo() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateVersionInfo()
	})
}

// SetNonce sets the "nonce" field.
func (u *NodeJobUpsertOne) SetNonce(v string) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateNonce() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateNonce()
	})
}

// SetErrorDetail sets the "error_detail" field.
func (u *NodeJobUpsertOne) SetErrorDetail(v string) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetErrorDetail(v)
	})
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateErrorDetail() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateErrorDetail()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NodeJobUpsertOne) SetUpdatedAt(v time.Time) *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NodeJobUpsertOne) UpdateUpdatedAt() *NodeJobUpsertOne {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NodeJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NodeJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NodeJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NodeJobUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NodeJobUpsertOne.ID is not supported by MySQL driver. Use NodeJobUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NodeJobUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NodeJobCreateBulk is the builder for creating many NodeJob entities in bulk.
type NodeJobCreateBulk struct {
	config
	err      error
	builders []*NodeJobCreate
	conflict []sql.ConflictOption
}

// Save creates the NodeJob entities in the database.
func (_c *NodeJobCreateBulk) Save(ctx context.Context) ([]*NodeJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NodeJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeJobCreateBulk) SaveX(ctx context.Context) []*NodeJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NodeJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NodeJobUpsert) {
//			SetNodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *NodeJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *NodeJobUpsertBulk {
	_c.conflict = opts
	return &NodeJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NodeJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NodeJobCreateBulk) OnConflictColumns(columns ...string) *NodeJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NodeJobUpsertBulk{
		create: _c,
	}
}

// NodeJobUpsertBulk is the builder for "upsert"-ing
// a bulk of NodeJob nodes.
type NodeJobUpsertBulk struct {
	create *NodeJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NodeJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(nodejob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NodeJobUpsertBulk) UpdateNewValues() *NodeJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(nodejob.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(nodejob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NodeJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NodeJobUpsertBulk) Ignore() *NodeJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NodeJobUpsertBulk) DoNothing() *NodeJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NodeJobCreateBulk.OnConflict
// documentation for more info.
func (u *NodeJobUpsertBulk) Update(set func(*NodeJobUpsert)) *NodeJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NodeJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetNodeID sets the "node_id" field.
func (u *NodeJobUpsertBulk) SetNodeID(v string) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateNodeID() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateNodeID()
	})
}

// SetStatus sets the "status" field.
func (u *NodeJobUpsertBulk) SetStatus(v string) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateStatus() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateStatus()
	})
}

// SetBaseRevision sets the "base_revision" field.
func (u *NodeJobUpsertBulk) SetBaseRevision(v uint64) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetBaseRevision(v)
	})
}

// AddBaseRevision adds v to the "base_revision" field.
func (u *NodeJobUpsertBulk) AddBaseRevision(v uint64) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.AddBaseRevision(v)
	})
}

// UpdateBaseRevision sets the "base_revision" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateBaseRevision() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateBaseRevision()
	})
}

// SetTargetRevision sets the "target_revision" field.
func (u *NodeJobUpsertBulk) SetTargetRevision(v uint64) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetTargetRevision(v)
	})
}

// AddTargetRevision adds v to the "target_revision" field.
func (u *NodeJobUpsertBulk) AddTargetRevision(v uint64) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.AddTargetRevision(v)
	})
}

// UpdateTargetRevision sets the "target_revision" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateTargetRevision() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateTargetRevision()
	})
}

// SetAcceptedRevision sets the "accepted_revision" field.
func (u *NodeJobUpsertBulk) SetAcceptedRevision(v uint64) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetAcceptedRevision(v)
	})
}

// AddAcceptedRevision adds v to the "accepted_revision" field.
func (u *NodeJobUpsertBulk) AddAcceptedRevision(v uint64) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.AddAcceptedRevision(v)
	})
}

// UpdateAcceptedRevision sets the "accepted_revision" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateAcceptedRevision() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateAcceptedRevision()
	})
}

// SetLastGoodRevision sets the "last_good_revision" field.
func (u *NodeJobUpsertBulk) SetLastGoodRevision(v uint64) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetLastGoodRevision(v)
	})
}

// AddLastGoodRevision adds v to the "last_good_revision" field.
func (u *NodeJobUpsertBulk) AddLastGoodRevision(v uint64) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.AddLastGoodRevision(v)
	})
}

// UpdateLastGoodRevision sets the "last_good_revision" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateLastGoodRevision() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateLastGoodRevision()
	})
}

// SetApplyID sets the "apply_id" field.
func (u *NodeJobUpsertBulk) SetApplyID(v string) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetApplyID(v)
	})
}

// UpdateApplyID sets the "apply_id" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateApplyID() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateApplyID()
	})
}

// SetVersionInfo sets the "version_info" field.
func (u *NodeJobUpsertBulk) SetVersionInfo(v string) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetVersionInfo(v)
	})
}

// UpdateVersionInfo sets the "version_info" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateVersionInfo() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateVersionInfo()
	})
}

// SetNonce sets the "nonce" field.
func (u *NodeJobUpsertBulk) SetNonce(v string) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateNonce() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateNonce()
	})
}

// SetErrorDetail sets the "error_detail" field.
func (u *NodeJobUpsertBulk) SetErrorDetail(v string) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetErrorDetail(v)
	})
}

// UpdateErrorDetail sets the "error_detail" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateErrorDetail() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateErrorDetail()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NodeJobUpsertBulk) SetUpdatedAt(v time.Time) *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NodeJobUpsertBulk) UpdateUpdatedAt() *NodeJobUpsertBulk {
	return u.Update(func(s *NodeJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NodeJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NodeJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NodeJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NodeJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
