// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/noderuntimestatus"
	"github.com/rayip/rayip/services/api/ent/predicate"
)

// NodeRuntimeStatusUpdate is the builder for updating NodeRuntimeStatus entities.
type NodeRuntimeStatusUpdate struct {
	config
	hooks    []Hook
	mutation *NodeRuntimeStatusMutation
}

// Where appends a list predicates to the NodeRuntimeStatusUpdate builder.
func (_u *NodeRuntimeStatusUpdate) Where(ps ...predicate.NodeRuntimeStatus) *NodeRuntimeStatusUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLeaseOnline sets the "lease_online" field.
func (_u *NodeRuntimeStatusUpdate) SetLeaseOnline(v bool) *NodeRuntimeStatusUpdate {
	_u.mutation.SetLeaseOnline(v)
	return _u
}

// SetNillableLeaseOnline sets the "lease_online" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableLeaseOnline(v *bool) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetLeaseOnline(*v)
	}
	return _u
}

// SetRuntimeVerdict sets the "runtime_verdict" field.
func (_u *NodeRuntimeStatusUpdate) SetRuntimeVerdict(v string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetRuntimeVerdict(v)
	return _u
}

// SetNillableRuntimeVerdict sets the "runtime_verdict" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableRuntimeVerdict(v *string) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetRuntimeVerdict(*v)
	}
	return _u
}

// SetExpectedRevision sets the "expected_revision" field.
func (_u *NodeRuntimeStatusUpdate) SetExpectedRevision(v uint64) *NodeRuntimeStatusUpdate {
	_u.mutation.ResetExpectedRevision()
	_u.mutation.SetExpectedRevision(v)
	return _u
}

// SetNillableExpectedRevision sets the "expected_revision" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableExpectedRevision(v *uint64) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetExpectedRevision(*v)
	}
	return _u
}

// AddExpectedRevision adds value to the "expected_revision" field.
func (_u *NodeRuntimeStatusUpdate) AddExpectedRevision(v int64) *NodeRuntimeStatusUpdate {
	_u.mutation.AddExpectedRevision(v)
	return _u
}

// SetCurrentRevision sets the "current_revision" field.
func (_u *NodeRuntimeStatusUpdate) SetCurrentRevision(v uint64) *NodeRuntimeStatusUpdate {
	_u.mutation.ResetCurrentRevision()
	_u.mutation.SetCurrentRevision(v)
	return _u
}

// SetNillableCurrentRevision sets the "current_revision" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableCurrentRevision(v *uint64) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetCurrentRevision(*v)
	}
	return _u
}

// AddCurrentRevision adds value to the "current_revision" field.
func (_u *NodeRuntimeStatusUpdate) AddCurrentRevision(v int64) *NodeRuntimeStatusUpdate {
	_u.mutation.AddCurrentRevision(v)
	return _u
}

// SetLastGoodRevision sets the "last_good_revision" field.
func (_u *NodeRuntimeStatusUpdate) SetLastGoodRevision(v uint64) *NodeRuntimeStatusUpdate {
	_u.mutation.ResetLastGoodRevision()
	_u.mutation.SetLastGoodRevision(v)
	return _u
}

// SetNillableLastGoodRevision sets the "last_good_revision" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableLastGoodRevision(v *uint64) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetLastGoodRevision(*v)
	}
	return _u
}

// AddLastGoodRevision adds value to the "last_good_revision" field.
func (_u *NodeRuntimeStatusUpdate) AddLastGoodRevision(v int64) *NodeRuntimeStatusUpdate {
	_u.mutation.AddLastGoodRevision(v)
	return _u
}

// SetExpectedDigestHash sets the "expected_digest_hash" field.
func (_u *NodeRuntimeStatusUpdate) SetExpectedDigestHash(v string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetExpectedDigestHash(v)
	return _u
}

// SetNillableExpectedDigestHash sets the "expected_digest_hash" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableExpectedDigestHash(v *string) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetExpectedDigestHash(*v)
	}
	return _u
}

// SetRuntimeDigestHash sets the "runtime_digest_hash" field.
func (_u *NodeRuntimeStatusUpdate) SetRuntimeDigestHash(v string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetRuntimeDigestHash(v)
	return _u
}

// SetNillableRuntimeDigestHash sets the "runtime_digest_hash" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableRuntimeDigestHash(v *string) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetRuntimeDigestHash(*v)
	}
	return _u
}

// SetAccountCount sets the "account_count" field.
func (_u *NodeRuntimeStatusUpdate) SetAccountCount(v uint64) *NodeRuntimeStatusUpdate {
	_u.mutation.ResetAccountCount()
	_u.mutation.SetAccountCount(v)
	return _u
}

// SetNillableAccountCount sets the "account_count" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableAccountCount(v *uint64) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetAccountCount(*v)
	}
	return _u
}

// AddAccountCount adds value to the "account_count" field.
func (_u *NodeRuntimeStatusUpdate) AddAccountCount(v int64) *NodeRuntimeStatusUpdate {
	_u.mutation.AddAccountCount(v)
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *NodeRuntimeStatusUpdate) SetCapabilities(v []string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *NodeRuntimeStatusUpdate) AppendCapabilities(v []string) *NodeRuntimeStatusUpdate {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// SetManifestHash sets the "manifest_hash" field.
func (_u *NodeRuntimeStatusUpdate) SetManifestHash(v string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetManifestHash(v)
	return _u
}

// SetNillableManifestHash sets the "manifest_hash" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableManifestHash(v *string) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetManifestHash(*v)
	}
	return _u
}

// SetBinaryHash sets the "binary_hash" field.
func (_u *NodeRuntimeStatusUpdate) SetBinaryHash(v string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetBinaryHash(v)
	return _u
}

// SetNillableBinaryHash sets the "binary_hash" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableBinaryHash(v *string) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetBinaryHash(*v)
	}
	return _u
}

// SetExtensionAbi sets the "extension_abi" field.
func (_u *NodeRuntimeStatusUpdate) SetExtensionAbi(v string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetExtensionAbi(v)
	return _u
}

// SetNillableExtensionAbi sets the "extension_abi" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableExtensionAbi(v *string) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetExtensionAbi(*v)
	}
	return _u
}

// SetBundleChannel sets the "bundle_channel" field.
func (_u *NodeRuntimeStatusUpdate) SetBundleChannel(v string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetBundleChannel(v)
	return _u
}

// SetNillableBundleChannel sets the "bundle_channel" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableBundleChannel(v *string) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetBundleChannel(*v)
	}
	return _u
}

// SetManualHold sets the "manual_hold" field.
func (_u *NodeRuntimeStatusUpdate) SetManualHold(v bool) *NodeRuntimeStatusUpdate {
	_u.mutation.SetManualHold(v)
	return _u
}

// SetNillableManualHold sets the "manual_hold" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableManualHold(v *bool) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetManualHold(*v)
	}
	return _u
}

// SetComplianceHold sets the "compliance_hold" field.
func (_u *NodeRuntimeStatusUpdate) SetComplianceHold(v bool) *NodeRuntimeStatusUpdate {
	_u.mutation.SetComplianceHold(v)
	return _u
}

// SetNillableComplianceHold sets the "compliance_hold" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableComplianceHold(v *bool) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetComplianceHold(*v)
	}
	return _u
}

// SetSellable sets the "sellable" field.
func (_u *NodeRuntimeStatusUpdate) SetSellable(v bool) *NodeRuntimeStatusUpdate {
	_u.mutation.SetSellable(v)
	return _u
}

// SetNillableSellable sets the "sellable" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdate) SetNillableSellable(v *bool) *NodeRuntimeStatusUpdate {
	if v != nil {
		_u.SetSellable(*v)
	}
	return _u
}

// SetUnsellableReasons sets the "unsellable_reasons" field.
func (_u *NodeRuntimeStatusUpdate) SetUnsellableReasons(v []string) *NodeRuntimeStatusUpdate {
	_u.mutation.SetUnsellableReasons(v)
	return _u
}

// AppendUnsellableReasons appends value to the "unsellable_reasons" field.
func (_u *NodeRuntimeStatusUpdate) AppendUnsellableReasons(v []string) *NodeRuntimeStatusUpdate {
	_u.mutation.AppendUnsellableReasons(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeRuntimeStatusUpdate) SetUpdatedAt(v time.Time) *NodeRuntimeStatusUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NodeRuntimeStatusMutation object of the builder.
func (_u *NodeRuntimeStatusUpdate) Mutation() *NodeRuntimeStatusMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeRuntimeStatusUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeRuntimeStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeRuntimeStatusUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeRuntimeStatusUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeRuntimeStatusUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := noderuntimestatus.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *NodeRuntimeStatusUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(noderuntimestatus.Table, noderuntimestatus.Columns, sqlgraph.NewFieldSpec(noderuntimestatus.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LeaseOnline(); ok {
		_spec.SetField(noderuntimestatus.FieldLeaseOnline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RuntimeVerdict(); ok {
		_spec.SetField(noderuntimestatus.FieldRuntimeVerdict, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpectedRevision(); ok {
		_spec.SetField(noderuntimestatus.FieldExpectedRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedExpectedRevision(); ok {
		_spec.AddField(noderuntimestatus.FieldExpectedRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.CurrentRevision(); ok {
		_spec.SetField(noderuntimestatus.FieldCurrentRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCurrentRevision(); ok {
		_spec.AddField(noderuntimestatus.FieldCurrentRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.LastGoodRevision(); ok {
		_spec.SetField(noderuntimestatus.FieldLastGoodRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedLastGoodRevision(); ok {
		_spec.AddField(noderuntimestatus.FieldLastGoodRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ExpectedDigestHash(); ok {
		_spec.SetField(noderuntimestatus.FieldExpectedDigestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuntimeDigestHash(); ok {
		_spec.SetField(noderuntimestatus.FieldRuntimeDigestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountCount(); ok {
		_spec.SetField(noderuntimestatus.FieldAccountCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAccountCount(); ok {
		_spec.AddField(noderuntimestatus.FieldAccountCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(noderuntimestatus.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, noderuntimestatus.FieldCapabilities, value)
		})
	}
	if value, ok := _u.mutation.ManifestHash(); ok {
		_spec.SetField(noderuntimestatus.FieldManifestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.BinaryHash(); ok {
		_spec.SetField(noderuntimestatus.FieldBinaryHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtensionAbi(); ok {
		_spec.SetField(noderuntimestatus.FieldExtensionAbi, field.TypeString, value)
	}
	if value, ok := _u.mutation.BundleChannel(); ok {
		_spec.SetField(noderuntimestatus.FieldBundleChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManualHold(); ok {
		_spec.SetField(noderuntimestatus.FieldManualHold, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ComplianceHold(); ok {
		_spec.SetField(noderuntimestatus.FieldComplianceHold, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sellable(); ok {
		_spec.SetField(noderuntimestatus.FieldSellable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UnsellableReasons(); ok {
		_spec.SetField(noderuntimestatus.FieldUnsellableReasons, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUnsellableReasons(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, noderuntimestatus.FieldUnsellableReasons, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(noderuntimestatus.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{noderuntimestatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeRuntimeStatusUpdateOne is the builder for updating a single NodeRuntimeStatus entity.
type NodeRuntimeStatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeRuntimeStatusMutation
}

// SetLeaseOnline sets the "lease_online" field.
func (_u *NodeRuntimeStatusUpdateOne) SetLeaseOnline(v bool) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetLeaseOnline(v)
	return _u
}

// SetNillableLeaseOnline sets the "lease_online" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableLeaseOnline(v *bool) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetLeaseOnline(*v)
	}
	return _u
}

// SetRuntimeVerdict sets the "runtime_verdict" field.
func (_u *NodeRuntimeStatusUpdateOne) SetRuntimeVerdict(v string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetRuntimeVerdict(v)
	return _u
}

// SetNillableRuntimeVerdict sets the "runtime_verdict" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableRuntimeVerdict(v *string) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetRuntimeVerdict(*v)
	}
	return _u
}

// SetExpectedRevision sets the "expected_revision" field.
func (_u *NodeRuntimeStatusUpdateOne) SetExpectedRevision(v uint64) *NodeRuntimeStatusUpdateOne {
	_u.mutation.ResetExpectedRevision()
	_u.mutation.SetExpectedRevision(v)
	return _u
}

// SetNillableExpectedRevision sets the "expected_revision" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableExpectedRevision(v *uint64) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetExpectedRevision(*v)
	}
	return _u
}

// AddExpectedRevision adds value to the "expected_revision" field.
func (_u *NodeRuntimeStatusUpdateOne) AddExpectedRevision(v int64) *NodeRuntimeStatusUpdateOne {
	_u.mutation.AddExpectedRevision(v)
	return _u
}

// SetCurrentRevision sets the "current_revision" field.
func (_u *NodeRuntimeStatusUpdateOne) SetCurrentRevision(v uint64) *NodeRuntimeStatusUpdateOne {
	_u.mutation.ResetCurrentRevision()
	_u.mutation.SetCurrentRevision(v)
	return _u
}

// SetNillableCurrentRevision sets the "current_revision" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableCurrentRevision(v *uint64) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetCurrentRevision(*v)
	}
	return _u
}

// AddCurrentRevision adds value to the "current_revision" field.
func (_u *NodeRuntimeStatusUpdateOne) AddCurrentRevision(v int64) *NodeRuntimeStatusUpdateOne {
	_u.mutation.AddCurrentRevision(v)
	return _u
}

// SetLastGoodRevision sets the "last_good_revision" field.
func (_u *NodeRuntimeStatusUpdateOne) SetLastGoodRevision(v uint64) *NodeRuntimeStatusUpdateOne {
	_u.mutation.ResetLastGoodRevision()
	_u.mutation.SetLastGoodRevision(v)
	return _u
}

// SetNillableLastGoodRevision sets the "last_good_revision" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableLastGoodRevision(v *uint64) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetLastGoodRevision(*v)
	}
	return _u
}

// AddLastGoodRevision adds value to the "last_good_revision" field.
func (_u *NodeRuntimeStatusUpdateOne) AddLastGoodRevision(v int64) *NodeRuntimeStatusUpdateOne {
	_u.mutation.AddLastGoodRevision(v)
	return _u
}

// SetExpectedDigestHash sets the "expected_digest_hash" field.
func (_u *NodeRuntimeStatusUpdateOne) SetExpectedDigestHash(v string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetExpectedDigestHash(v)
	return _u
}

// SetNillableExpectedDigestHash sets the "expected_digest_hash" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableExpectedDigestHash(v *string) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetExpectedDigestHash(*v)
	}
	return _u
}

// SetRuntimeDigestHash sets the "runtime_digest_hash" field.
func (_u *NodeRuntimeStatusUpdateOne) SetRuntimeDigestHash(v string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetRuntimeDigestHash(v)
	return _u
}

// SetNillableRuntimeDigestHash sets the "runtime_digest_hash" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableRuntimeDigestHash(v *string) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetRuntimeDigestHash(*v)
	}
	return _u
}

// SetAccountCount sets the "account_count" field.
func (_u *NodeRuntimeStatusUpdateOne) SetAccountCount(v uint64) *NodeRuntimeStatusUpdateOne {
	_u.mutation.ResetAccountCount()
	_u.mutation.SetAccountCount(v)
	return _u
}

// SetNillableAccountCount sets the "account_count" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableAccountCount(v *uint64) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetAccountCount(*v)
	}
	return _u
}

// AddAccountCount adds value to the "account_count" field.
func (_u *NodeRuntimeStatusUpdateOne) AddAccountCount(v int64) *NodeRuntimeStatusUpdateOne {
	_u.mutation.AddAccountCount(v)
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *NodeRuntimeStatusUpdateOne) SetCapabilities(v []string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *NodeRuntimeStatusUpdateOne) AppendCapabilities(v []string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// SetManifestHash sets the "manifest_hash" field.
func (_u *NodeRuntimeStatusUpdateOne) SetManifestHash(v string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetManifestHash(v)
	return _u
}

// SetNillableManifestHash sets the "manifest_hash" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableManifestHash(v *string) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetManifestHash(*v)
	}
	return _u
}

// SetBinaryHash sets the "binary_hash" field.
func (_u *NodeRuntimeStatusUpdateOne) SetBinaryHash(v string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetBinaryHash(v)
	return _u
}

// SetNillableBinaryHash sets the "binary_hash" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableBinaryHash(v *string) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetBinaryHash(*v)
	}
	return _u
}

// SetExtensionAbi sets the "extension_abi" field.
func (_u *NodeRuntimeStatusUpdateOne) SetExtensionAbi(v string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetExtensionAbi(v)
	return _u
}

// SetNillableExtensionAbi sets the "extension_abi" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableExtensionAbi(v *string) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetExtensionAbi(*v)
	}
	return _u
}

// SetBundleChannel sets the "bundle_channel" field.
func (_u *NodeRuntimeStatusUpdateOne) SetBundleChannel(v string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetBundleChannel(v)
	return _u
}

// SetNillableBundleChannel sets the "bundle_channel" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableBundleChannel(v *string) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetBundleChannel(*v)
	}
	return _u
}

// SetManualHold sets the "manual_hold" field.
func (_u *NodeRuntimeStatusUpdateOne) SetManualHold(v bool) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetManualHold(v)
	return _u
}

// SetNillableManualHold sets the "manual_hold" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableManualHold(v *bool) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetManualHold(*v)
	}
	return _u
}

// SetComplianceHold sets the "compliance_hold" field.
func (_u *NodeRuntimeStatusUpdateOne) SetComplianceHold(v bool) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetComplianceHold(v)
	return _u
}

// SetNillableComplianceHold sets the "compliance_hold" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableComplianceHold(v *bool) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetComplianceHold(*v)
	}
	return _u
}

// SetSellable sets the "sellable" field.
func (_u *NodeRuntimeStatusUpdateOne) SetSellable(v bool) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetSellable(v)
	return _u
}

// SetNillableSellable sets the "sellable" field if the given value is not nil.
func (_u *NodeRuntimeStatusUpdateOne) SetNillableSellable(v *bool) *NodeRuntimeStatusUpdateOne {
	if v != nil {
		_u.SetSellable(*v)
	}
	return _u
}

// SetUnsellableReasons sets the "unsellable_reasons" field.
func (_u *NodeRuntimeStatusUpdateOne) SetUnsellableReasons(v []string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetUnsellableReasons(v)
	return _u
}

// AppendUnsellableReasons appends value to the "unsellable_reasons" field.
func (_u *NodeRuntimeStatusUpdateOne) AppendUnsellableReasons(v []string) *NodeRuntimeStatusUpdateOne {
	_u.mutation.AppendUnsellableReasons(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeRuntimeStatusUpdateOne) SetUpdatedAt(v time.Time) *NodeRuntimeStatusUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NodeRuntimeStatusMutation object of the builder.
func (_u *NodeRuntimeStatusUpdateOne) Mutation() *NodeRuntimeStatusMutation {
	return _u.mutation
}

// Where appends a list predicates to the NodeRuntimeStatusUpdate builder.
func (_u *NodeRuntimeStatusUpdateOne) Where(ps ...predicate.NodeRuntimeStatus) *NodeRuntimeStatusUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeRuntimeStatusUpdateOne) Select(field string, fields ...string) *NodeRuntimeStatusUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NodeRuntimeStatus entity.
func (_u *NodeRuntimeStatusUpdateOne) Save(ctx context.Context) (*NodeRuntimeStatus, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeRuntimeStatusUpdateOne) SaveX(ctx context.Context) *NodeRuntimeStatus {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeRuntimeStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeRuntimeStatusUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeRuntimeStatusUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := noderuntimestatus.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *NodeRuntimeStatusUpdateOne) sqlSave(ctx context.Context) (_node *NodeRuntimeStatus, err error) {
	_spec := sqlgraph.NewUpdateSpec(noderuntimestatus.Table, noderuntimestatus.Columns, sqlgraph.NewFieldSpec(noderuntimestatus.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NodeRuntimeStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, noderuntimestatus.FieldID)
		for _, f := range fields {
			if !noderuntimestatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != noderuntimestatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LeaseOnline(); ok {
		_spec.SetField(noderuntimestatus.FieldLeaseOnline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RuntimeVerdict(); ok {
		_spec.SetField(noderuntimestatus.FieldRuntimeVerdict, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpectedRevision(); ok {
		_spec.SetField(noderuntimestatus.FieldExpectedRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedExpectedRevision(); ok {
		_spec.AddField(noderuntimestatus.FieldExpectedRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.CurrentRevision(); ok {
		_spec.SetField(noderuntimestatus.FieldCurrentRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCurrentRevision(); ok {
		_spec.AddField(noderuntimestatus.FieldCurrentRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.LastGoodRevision(); ok {
		_spec.SetField(noderuntimestatus.FieldLastGoodRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedLastGoodRevision(); ok {
		_spec.AddField(noderuntimestatus.FieldLastGoodRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ExpectedDigestHash(); ok {
		_spec.SetField(noderuntimestatus.FieldExpectedDigestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuntimeDigestHash(); ok {
		_spec.SetField(noderuntimestatus.FieldRuntimeDigestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountCount(); ok {
		_spec.SetField(noderuntimestatus.FieldAccountCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAccountCount(); ok {
		_spec.AddField(noderuntimestatus.FieldAccountCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(noderuntimestatus.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, noderuntimestatus.FieldCapabilities, value)
		})
	}
	if value, ok := _u.mutation.ManifestHash(); ok {
		_spec.SetField(noderuntimestatus.FieldManifestHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.BinaryHash(); ok {
		_spec.SetField(noderuntimestatus.FieldBinaryHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExtensionAbi(); ok {
		_spec.SetField(noderuntimestatus.FieldExtensionAbi, field.TypeString, value)
	}
	if value, ok := _u.mutation.BundleChannel(); ok {
		_spec.SetField(noderuntimestatus.FieldBundleChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManualHold(); ok {
		_spec.SetField(noderuntimestatus.FieldManualHold, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ComplianceHold(); ok {
		_spec.SetField(noderuntimestatus.FieldComplianceHold, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sellable(); ok {
		_spec.SetField(noderuntimestatus.FieldSellable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UnsellableReasons(); ok {
		_spec.SetField(noderuntimestatus.FieldUnsellableReasons, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUnsellableReasons(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, noderuntimestatus.FieldUnsellableReasons, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(noderuntimestatus.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &NodeRuntimeStatus{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{noderuntimestatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
