// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/outboxevent"
)

// OutboxEvent is the model entity for the OutboxEvent schema.
type OutboxEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Topic holds the value of the "topic" field.
	Topic string `json:"topic,omitempty"`
	// AggregateID holds the value of the "aggregate_id" field.
	AggregateID string `json:"aggregate_id,omitempty"`
	// AggregateKey holds the value of the "aggregate_key" field.
	AggregateKey string `json:"aggregate_key,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutboxEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outboxevent.FieldPayload:
			values[i] = new([]byte)
		case outboxevent.FieldID, outboxevent.FieldTopic, outboxevent.FieldAggregateID, outboxevent.FieldAggregateKey:
			values[i] = new(sql.NullString)
		case outboxevent.FieldPublishedAt, outboxevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutboxEvent fields.
func (_m *OutboxEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outboxevent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case outboxevent.FieldTopic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic", values[i])
			} else if value.Valid {
				_m.Topic = value.String
			}
		case outboxevent.FieldAggregateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aggregate_id", values[i])
			} else if value.Valid {
				_m.AggregateID = value.String
			}
		case outboxevent.FieldAggregateKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aggregate_key", values[i])
			} else if value.Valid {
				_m.AggregateKey = value.String
			}
		case outboxevent.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case outboxevent.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case outboxevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutboxEvent.
// This includes values selected through modifiers, order, etc.
func (_m *OutboxEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OutboxEvent.
// Note that you need to call OutboxEvent.Unwrap() before calling this method if this OutboxEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OutboxEvent) Update() *OutboxEventUpdateOne {
	return NewOutboxEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OutboxEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OutboxEvent) Unwrap() *OutboxEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutboxEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OutboxEvent) String() string {
	var builder strings.Builder
	builder.WriteString("OutboxEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("topic=")
	builder.WriteString(_m.Topic)
	builder.WriteString(", ")
	builder.WriteString("aggregate_id=")
	builder.WriteString(_m.AggregateID)
	builder.WriteString(", ")
	builder.WriteString("aggregate_key=")
	builder.WriteString(_m.AggregateKey)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OutboxEvents is a parsable slice of OutboxEvent.
type OutboxEvents []*OutboxEvent
