// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/proxyorder"
)

// ProxyOrderCreate is the builder for creating a ProxyOrder entity.
type ProxyOrderCreate struct {
	config
	mutation *ProxyOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *ProxyOrderCreate) SetUserID(v string) *ProxyOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *ProxyOrderCreate) SetProductID(v string) *ProxyOrderCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetInventoryID sets the "inventory_id" field.
func (_c *ProxyOrderCreate) SetInventoryID(v string) *ProxyOrderCreate {
	_c.mutation.SetInventoryID(v)
	return _c
}

// SetReservationID sets the "reservation_id" field.
func (_c *ProxyOrderCreate) SetReservationID(v string) *ProxyOrderCreate {
	_c.mutation.SetReservationID(v)
	return _c
}

// SetNillableReservationID sets the "reservation_id" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableReservationID(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetReservationID(*v)
	}
	return _c
}

// SetWalletHoldID sets the "wallet_hold_id" field.
func (_c *ProxyOrderCreate) SetWalletHoldID(v string) *ProxyOrderCreate {
	_c.mutation.SetWalletHoldID(v)
	return _c
}

// SetNillableWalletHoldID sets the "wallet_hold_id" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableWalletHoldID(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetWalletHoldID(*v)
	}
	return _c
}

// SetProxyAccountID sets the "proxy_account_id" field.
func (_c *ProxyOrderCreate) SetProxyAccountID(v string) *ProxyOrderCreate {
	_c.mutation.SetProxyAccountID(v)
	return _c
}

// SetNillableProxyAccountID sets the "proxy_account_id" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableProxyAccountID(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetProxyAccountID(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *ProxyOrderCreate) SetIdempotencyKey(v string) *ProxyOrderCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *ProxyOrderCreate) SetProtocol(v string) *ProxyOrderCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetDurationDays sets the "duration_days" field.
func (_c *ProxyOrderCreate) SetDurationDays(v int) *ProxyOrderCreate {
	_c.mutation.SetDurationDays(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *ProxyOrderCreate) SetQuantity(v int) *ProxyOrderCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableQuantity(v *int) *ProxyOrderCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetAmountCents sets the "amount_cents" field.
func (_c *ProxyOrderCreate) SetAmountCents(v int64) *ProxyOrderCreate {
	_c.mutation.SetAmountCents(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProxyOrderCreate) SetStatus(v string) *ProxyOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetFailureReason sets the "failure_reason" field.
func (_c *ProxyOrderCreate) SetFailureReason(v string) *ProxyOrderCreate {
	_c.mutation.SetFailureReason(v)
	return _c
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableFailureReason(v *string) *ProxyOrderCreate {
	if v != nil {
		_c.SetFailureReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyOrderCreate) SetCreatedAt(v time.Time) *ProxyOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableCreatedAt(v *time.Time) *ProxyOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyOrderCreate) SetUpdatedAt(v time.Time) *ProxyOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableUpdatedAt(v *time.Time) *ProxyOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeliveredAt sets the "delivered_at" field.
func (_c *ProxyOrderCreate) SetDeliveredAt(v time.Time) *ProxyOrderCreate {
	_c.mutation.SetDeliveredAt(v)
	return _c
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableDeliveredAt(v *time.Time) *ProxyOrderCreate {
	if v != nil {
		_c.SetDeliveredAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ProxyOrderCreate) SetExpiresAt(v time.Time) *ProxyOrderCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ProxyOrderCreate) SetNillableExpiresAt(v *time.Time) *ProxyOrderCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProxyOrderCreate) SetID(v string) *ProxyOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProxyOrderMutation object of the builder.
func (_c *ProxyOrderCreate) Mutation() *ProxyOrderMutation {
	return _c.mutation
}

// Save creates the ProxyOrder in the database.
func (_c *ProxyOrderCreate) Save(ctx context.Context) (*ProxyOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyOrderCreate) SaveX(ctx context.Context) *ProxyOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyOrderCreate) defaults() {
	if _, ok := _c.mutation.ReservationID(); !ok {
		v := proxyorder.DefaultReservationID
		_c.mutation.SetReservationID(v)
	}
	if _, ok := _c.mutation.WalletHoldID(); !ok {
		v := proxyorder.DefaultWalletHoldID
		_c.mutation.SetWalletHoldID(v)
	}
	if _, ok := _c.mutation.ProxyAccountID(); !ok {
		v := proxyorder.DefaultProxyAccountID
		_c.mutation.SetProxyAccountID(v)
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		v := proxyorder.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.FailureReason(); !ok {
		v := proxyorder.DefaultFailureReason
		_c.mutation.SetFailureReason(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxyorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyOrderCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ProxyOrder.user_id"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "ProxyOrder.product_id"`)}
	}
	if _, ok := _c.mutation.InventoryID(); !ok {
		return &ValidationError{Name: "inventory_id", err: errors.New(`ent: missing required field "ProxyOrder.inventory_id"`)}
	}
	if _, ok := _c.mutation.ReservationID(); !ok {
		return &ValidationError{Name: "reservation_id", err: errors.New(`ent: missing required field "ProxyOrder.reservation_id"`)}
	}
	if _, ok := _c.mutation.WalletHoldID(); !ok {
		return &ValidationError{Name: "wallet_hold_id", err: errors.New(`ent: missing required field "ProxyOrder.wallet_hold_id"`)}
	}
	if _, ok := _c.mutation.ProxyAccountID(); !ok {
		return &ValidationError{Name: "proxy_account_id", err: errors.New(`ent: missing required field "ProxyOrder.proxy_account_id"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "ProxyOrder.idempotency_key"`)}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "ProxyOrder.protocol"`)}
	}
	if _, ok := _c.mutation.DurationDays(); !ok {
		return &ValidationError{Name: "duration_days", err: errors.New(`ent: missing required field "ProxyOrder.duration_days"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "ProxyOrder.quantity"`)}
	}
	if _, ok := _c.mutation.AmountCents(); !ok {
		return &ValidationError{Name: "amount_cents", err: errors.New(`ent: missing required field "ProxyOrder.amount_cents"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProxyOrder.status"`)}
	}
	if _, ok := _c.mutation.FailureReason(); !ok {
		return &ValidationError{Name: "failure_reason", err: errors.New(`ent: missing required field "ProxyOrder.failure_reason"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyOrder.updated_at"`)}
	}
	return nil
}

func (_c *ProxyOrderCreate) sqlSave(ctx context.Context) (*ProxyOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ProxyOrder.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyOrderCreate) createSpec() (*ProxyOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyorder.Table, sqlgraph.NewFieldSpec(proxyorder.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(proxyorder.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(proxyorder.FieldProductID, field.TypeString, value)
		_node.ProductID = value
	}
	if value, ok := _c.mutation.InventoryID(); ok {
		_spec.SetField(proxyorder.FieldInventoryID, field.TypeString, value)
		_node.InventoryID = value
	}
	if value, ok := _c.mutation.ReservationID(); ok {
		_spec.SetField(proxyorder.FieldReservationID, field.TypeString, value)
		_node.ReservationID = value
	}
	if value, ok := _c.mutation.WalletHoldID(); ok {
		_spec.SetField(proxyorder.FieldWalletHoldID, field.TypeString, value)
		_node.WalletHoldID = value
	}
	if value, ok := _c.mutation.ProxyAccountID(); ok {
		_spec.SetField(proxyorder.FieldProxyAccountID, field.TypeString, value)
		_node.ProxyAccountID = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(proxyorder.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(proxyorder.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.DurationDays(); ok {
		_spec.SetField(proxyorder.FieldDurationDays, field.TypeInt, value)
		_node.DurationDays = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(proxyorder.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.AmountCents(); ok {
		_spec.SetField(proxyorder.FieldAmountCents, field.TypeInt64, value)
		_node.AmountCents = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(proxyorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FailureReason(); ok {
		_spec.SetField(proxyorder.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeliveredAt(); ok {
		_spec.SetField(proxyorder.FieldDeliveredAt, field.TypeTime, value)
		_node.DeliveredAt = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(proxyorder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyOrder.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyOrderUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyOrderCreate) OnConflict(opts ...sql.ConflictOption) *ProxyOrderUpsertOne {
	_c.conflict = opts
	return &ProxyOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyOrderCreate) OnConflictColumns(columns ...string) *ProxyOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyOrderUpsertOne{
		create: _c,
	}
}

type (
	// ProxyOrderUpsertOne is the builder for "upsert"-ing
	//  one ProxyOrder node.
	ProxyOrderUpsertOne struct {
		create *ProxyOrderCreate
	}

	// ProxyOrderUpsert is the "OnConflict" setter.
	ProxyOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *ProxyOrderUpsert) SetUserID(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateUserID() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldUserID)
	return u
}

// SetProductID sets the "product_id" field.
func (u *ProxyOrderUpsert) SetProductID(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateProductID() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldProductID)
	return u
}

// SetInventoryID sets the "inventory_id" field.
func (u *ProxyOrderUpsert) SetInventoryID(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldInventoryID, v)
	return u
}

// UpdateInventoryID sets the "inventory_id" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateInventoryID() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldInventoryID)
	return u
}

// SetReservationID sets the "reservation_id" field.
func (u *ProxyOrderUpsert) SetReservationID(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldReservationID, v)
	return u
}

// UpdateReservationID sets the "reservation_id" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateReservationID() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldReservationID)
	return u
}

// SetWalletHoldID sets the "wallet_hold_id" field.
func (u *ProxyOrderUpsert) SetWalletHoldID(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldWalletHoldID, v)
	return u
}

// UpdateWalletHoldID sets the "wallet_hold_id" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateWalletHoldID() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldWalletHoldID)
	return u
}

// SetProxyAccountID sets the "proxy_account_id" field.
func (u *ProxyOrderUpsert) SetProxyAccountID(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldProxyAccountID, v)
	return u
}

// UpdateProxyAccountID sets the "proxy_account_id" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateProxyAccountID() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldProxyAccountID)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ProxyOrderUpsert) SetIdempotencyKey(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateIdempotencyKey() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldIdempotencyKey)
	return u
}

// SetProtocol sets the "protocol" field.
func (u *ProxyOrderUpsert) SetProtocol(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldProtocol, v)
	return u
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateProtocol() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldProtocol)
	return u
}

// SetDurationDays sets the "duration_days" field.
func (u *ProxyOrderUpsert) SetDurationDays(v int) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldDurationDays, v)
	return u
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateDurationDays() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldDurationDays)
	return u
}

// AddDurationDays adds v to the "duration_days" field.
func (u *ProxyOrderUpsert) AddDurationDays(v int) *ProxyOrderUpsert {
	u.Add(proxyorder.FieldDurationDays, v)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *ProxyOrderUpsert) SetQuantity(v int) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateQuantity() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *ProxyOrderUpsert) AddQuantity(v int) *ProxyOrderUpsert {
	u.Add(proxyorder.FieldQuantity, v)
	return u
}

// SetAmountCents sets the "amount_cents" field.
func (u *ProxyOrderUpsert) SetAmountCents(v int64) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldAmountCents, v)
	return u
}

// UpdateAmountCents sets the "amount_cents" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateAmountCents() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldAmountCents)
	return u
}

// AddAmountCents adds v to the "amount_cents" field.
func (u *ProxyOrderUpsert) AddAmountCents(v int64) *ProxyOrderUpsert {
	u.Add(proxyorder.FieldAmountCents, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ProxyOrderUpsert) SetStatus(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateStatus() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldStatus)
	return u
}

// SetFailureReason sets the "failure_reason" field.
func (u *ProxyOrderUpsert) SetFailureReason(v string) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldFailureReason, v)
	return u
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateFailureReason() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldFailureReason)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyOrderUpsert) SetUpdatedAt(v time.Time) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateUpdatedAt() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldUpdatedAt)
	return u
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *ProxyOrderUpsert) SetDeliveredAt(v time.Time) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldDeliveredAt, v)
	return u
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateDeliveredAt() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldDeliveredAt)
	return u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *ProxyOrderUpsert) ClearDeliveredAt() *ProxyOrderUpsert {
	u.SetNull(proxyorder.FieldDeliveredAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyOrderUpsert) SetExpiresAt(v time.Time) *ProxyOrderUpsert {
	u.Set(proxyorder.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyOrderUpsert) UpdateExpiresAt() *ProxyOrderUpsert {
	u.SetExcluded(proxyorder.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyOrderUpsert) ClearExpiresAt() *ProxyOrderUpsert {
	u.SetNull(proxyorder.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ProxyOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(proxyorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProxyOrderUpsertOne) UpdateNewValues() *ProxyOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(proxyorder.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(proxyorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProxyOrderUpsertOne) Ignore() *ProxyOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyOrderUpsertOne) DoNothing() *ProxyOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyOrderCreate.OnConflict
// documentation for more info.
func (u *ProxyOrderUpsertOne) Update(set func(*ProxyOrderUpsert)) *ProxyOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ProxyOrderUpsertOne) SetUserID(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateUserID() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *ProxyOrderUpsertOne) SetProductID(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateProductID() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateProductID()
	})
}

// SetInventoryID sets the "inventory_id" field.
func (u *ProxyOrderUpsertOne) SetInventoryID(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetInventoryID(v)
	})
}

// UpdateInventoryID sets the "inventory_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateInventoryID() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateInventoryID()
	})
}

// SetReservationID sets the "reservation_id" field.
func (u *ProxyOrderUpsertOne) SetReservationID(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetReservationID(v)
	})
}

// UpdateReservationID sets the "reservation_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateReservationID() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateReservationID()
	})
}

// SetWalletHoldID sets the "wallet_hold_id" field.
func (u *ProxyOrderUpsertOne) SetWalletHoldID(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetWalletHoldID(v)
	})
}

// UpdateWalletHoldID sets the "wallet_hold_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateWalletHoldID() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateWalletHoldID()
	})
}

// SetProxyAccountID sets the "proxy_account_id" field.
func (u *ProxyOrderUpsertOne) SetProxyAccountID(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetProxyAccountID(v)
	})
}

// UpdateProxyAccountID sets the "proxy_account_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateProxyAccountID() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateProxyAccountID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ProxyOrderUpsertOne) SetIdempotencyKey(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateIdempotencyKey() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ProxyOrderUpsertOne) SetProtocol(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateProtocol() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateProtocol()
	})
}

// SetDurationDays sets the "duration_days" field.
func (u *ProxyOrderUpsertOne) SetDurationDays(v int) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetDurationDays(v)
	})
}

// AddDurationDays adds v to the "duration_days" field.
func (u *ProxyOrderUpsertOne) AddDurationDays(v int) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.AddDurationDays(v)
	})
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateDurationDays() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateDurationDays()
	})
}

// SetQuantity sets the "quantity" field.
func (u *ProxyOrderUpsertOne) SetQuantity(v int) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *ProxyOrderUpsertOne) AddQuantity(v int) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateQuantity() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateQuantity()
	})
}

// SetAmountCents sets the "amount_cents" field.
func (u *ProxyOrderUpsertOne) SetAmountCents(v int64) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetAmountCents(v)
	})
}

// AddAmountCents adds v to the "amount_cents" field.
func (u *ProxyOrderUpsertOne) AddAmountCents(v int64) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.AddAmountCents(v)
	})
}

// UpdateAmountCents sets the "amount_cents" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateAmountCents() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateAmountCents()
	})
}

// SetStatus sets the "status" field.
func (u *ProxyOrderUpsertOne) SetStatus(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateStatus() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *ProxyOrderUpsertOne) SetFailureReason(v string) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateFailureReason() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateFailureReason()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyOrderUpsertOne) SetUpdatedAt(v time.Time) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateUpdatedAt() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *ProxyOrderUpsertOne) SetDeliveredAt(v time.Time) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetDeliveredAt(v)
	})
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateDeliveredAt() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateDeliveredAt()
	})
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *ProxyOrderUpsertOne) ClearDeliveredAt() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.ClearDeliveredAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyOrderUpsertOne) SetExpiresAt(v time.Time) *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyOrderUpsertOne) UpdateExpiresAt() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyOrderUpsertOne) ClearExpiresAt() *ProxyOrderUpsertOne {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *ProxyOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProxyOrderUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ProxyOrderUpsertOne.ID is not supported by MySQL driver. Use ProxyOrderUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProxyOrderUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProxyOrderCreateBulk is the builder for creating many ProxyOrder entities in bulk.
type ProxyOrderCreateBulk struct {
	config
	err      error
	builders []*ProxyOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the ProxyOrder entities in the database.
func (_c *ProxyOrderCreateBulk) Save(ctx context.Context) ([]*ProxyOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyOrderCreateBulk) SaveX(ctx context.Context) []*ProxyOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProxyOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProxyOrderUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProxyOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProxyOrderUpsertBulk {
	_c.conflict = opts
	return &ProxyOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProxyOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProxyOrderCreateBulk) OnConflictColumns(columns ...string) *ProxyOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProxyOrderUpsertBulk{
		create: _c,
	}
}

// ProxyOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of ProxyOrder nodes.
type ProxyOrderUpsertBulk struct {
	create *ProxyOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProxyOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(proxyorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProxyOrderUpsertBulk) UpdateNewValues() *ProxyOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(proxyorder.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(proxyorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProxyOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProxyOrderUpsertBulk) Ignore() *ProxyOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProxyOrderUpsertBulk) DoNothing() *ProxyOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProxyOrderCreateBulk.OnConflict
// documentation for more info.
func (u *ProxyOrderUpsertBulk) Update(set func(*ProxyOrderUpsert)) *ProxyOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProxyOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ProxyOrderUpsertBulk) SetUserID(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateUserID() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *ProxyOrderUpsertBulk) SetProductID(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateProductID() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateProductID()
	})
}

// SetInventoryID sets the "inventory_id" field.
func (u *ProxyOrderUpsertBulk) SetInventoryID(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetInventoryID(v)
	})
}

// UpdateInventoryID sets the "inventory_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateInventoryID() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateInventoryID()
	})
}

// SetReservationID sets the "reservation_id" field.
func (u *ProxyOrderUpsertBulk) SetReservationID(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetReservationID(v)
	})
}

// UpdateReservationID sets the "reservation_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateReservationID() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateReservationID()
	})
}

// SetWalletHoldID sets the "wallet_hold_id" field.
func (u *ProxyOrderUpsertBulk) SetWalletHoldID(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetWalletHoldID(v)
	})
}

// UpdateWalletHoldID sets the "wallet_hold_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateWalletHoldID() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateWalletHoldID()
	})
}

// SetProxyAccountID sets the "proxy_account_id" field.
func (u *ProxyOrderUpsertBulk) SetProxyAccountID(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetProxyAccountID(v)
	})
}

// UpdateProxyAccountID sets the "proxy_account_id" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateProxyAccountID() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateProxyAccountID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ProxyOrderUpsertBulk) SetIdempotencyKey(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateIdempotencyKey() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetProtocol sets the "protocol" field.
func (u *ProxyOrderUpsertBulk) SetProtocol(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateProtocol() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateProtocol()
	})
}

// SetDurationDays sets the "duration_days" field.
func (u *ProxyOrderUpsertBulk) SetDurationDays(v int) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetDurationDays(v)
	})
}

// AddDurationDays adds v to the "duration_days" field.
func (u *ProxyOrderUpsertBulk) AddDurationDays(v int) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.AddDurationDays(v)
	})
}

// UpdateDurationDays sets the "duration_days" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateDurationDays() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateDurationDays()
	})
}

// SetQuantity sets the "quantity" field.
func (u *ProxyOrderUpsertBulk) SetQuantity(v int) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *ProxyOrderUpsertBulk) AddQuantity(v int) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateQuantity() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateQuantity()
	})
}

// SetAmountCents sets the "amount_cents" field.
func (u *ProxyOrderUpsertBulk) SetAmountCents(v int64) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetAmountCents(v)
	})
}

// AddAmountCents adds v to the "amount_cents" field.
func (u *ProxyOrderUpsertBulk) AddAmountCents(v int64) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.AddAmountCents(v)
	})
}

// UpdateAmountCents sets the "amount_cents" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateAmountCents() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateAmountCents()
	})
}

// SetStatus sets the "status" field.
func (u *ProxyOrderUpsertBulk) SetStatus(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateStatus() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *ProxyOrderUpsertBulk) SetFailureReason(v string) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateFailureReason() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateFailureReason()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProxyOrderUpsertBulk) SetUpdatedAt(v time.Time) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateUpdatedAt() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *ProxyOrderUpsertBulk) SetDeliveredAt(v time.Time) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetDeliveredAt(v)
	})
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateDeliveredAt() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateDeliveredAt()
	})
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *ProxyOrderUpsertBulk) ClearDeliveredAt() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.ClearDeliveredAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ProxyOrderUpsertBulk) SetExpiresAt(v time.Time) *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ProxyOrderUpsertBulk) UpdateExpiresAt() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ProxyOrderUpsertBulk) ClearExpiresAt() *ProxyOrderUpsertBulk {
	return u.Update(func(s *ProxyOrderUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *ProxyOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProxyOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProxyOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProxyOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
