// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/predicate"
	"github.com/rayip/rayip/services/api/ent/proxyorder"
)

// ProxyOrderUpdate is the builder for updating ProxyOrder entities.
type ProxyOrderUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyOrderMutation
}

// Where appends a list predicates to the ProxyOrderUpdate builder.
func (_u *ProxyOrderUpdate) Where(ps ...predicate.ProxyOrder) *ProxyOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProxyOrderUpdate) SetUserID(v string) *ProxyOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableUserID(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProxyOrderUpdate) SetProductID(v string) *ProxyOrderUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableProductID(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetInventoryID sets the "inventory_id" field.
func (_u *ProxyOrderUpdate) SetInventoryID(v string) *ProxyOrderUpdate {
	_u.mutation.SetInventoryID(v)
	return _u
}

// SetNillableInventoryID sets the "inventory_id" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableInventoryID(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetInventoryID(*v)
	}
	return _u
}

// SetReservationID sets the "reservation_id" field.
func (_u *ProxyOrderUpdate) SetReservationID(v string) *ProxyOrderUpdate {
	_u.mutation.SetReservationID(v)
	return _u
}

// SetNillableReservationID sets the "reservation_id" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableReservationID(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetReservationID(*v)
	}
	return _u
}

// SetWalletHoldID sets the "wallet_hold_id" field.
func (_u *ProxyOrderUpdate) SetWalletHoldID(v string) *ProxyOrderUpdate {
	_u.mutation.SetWalletHoldID(v)
	return _u
}

// SetNillableWalletHoldID sets the "wallet_hold_id" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableWalletHoldID(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetWalletHoldID(*v)
	}
	return _u
}

// SetProxyAccountID sets the "proxy_account_id" field.
func (_u *ProxyOrderUpdate) SetProxyAccountID(v string) *ProxyOrderUpdate {
	_u.mutation.SetProxyAccountID(v)
	return _u
}

// SetNillableProxyAccountID sets the "proxy_account_id" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableProxyAccountID(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetProxyAccountID(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ProxyOrderUpdate) SetIdempotencyKey(v string) *ProxyOrderUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableIdempotencyKey(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProxyOrderUpdate) SetProtocol(v string) *ProxyOrderUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableProtocol(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *ProxyOrderUpdate) SetDurationDays(v int) *ProxyOrderUpdate {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableDurationDays(v *int) *ProxyOrderUpdate {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *ProxyOrderUpdate) AddDurationDays(v int) *ProxyOrderUpdate {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *ProxyOrderUpdate) SetQuantity(v int) *ProxyOrderUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableQuantity(v *int) *ProxyOrderUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *ProxyOrderUpdate) AddQuantity(v int) *ProxyOrderUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *ProxyOrderUpdate) SetAmountCents(v int64) *ProxyOrderUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableAmountCents(v *int64) *ProxyOrderUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *ProxyOrderUpdate) AddAmountCents(v int64) *ProxyOrderUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyOrderUpdate) SetStatus(v string) *ProxyOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableStatus(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *ProxyOrderUpdate) SetFailureReason(v string) *ProxyOrderUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableFailureReason(v *string) *ProxyOrderUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyOrderUpdate) SetUpdatedAt(v time.Time) *ProxyOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *ProxyOrderUpdate) SetDeliveredAt(v time.Time) *ProxyOrderUpdate {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableDeliveredAt(v *time.Time) *ProxyOrderUpdate {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *ProxyOrderUpdate) ClearDeliveredAt() *ProxyOrderUpdate {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProxyOrderUpdate) SetExpiresAt(v time.Time) *ProxyOrderUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProxyOrderUpdate) SetNillableExpiresAt(v *time.Time) *ProxyOrderUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ProxyOrderUpdate) ClearExpiresAt() *ProxyOrderUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the ProxyOrderMutation object of the builder.
func (_u *ProxyOrderUpdate) Mutation() *ProxyOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ProxyOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(proxyorder.Table, proxyorder.Columns, sqlgraph.NewFieldSpec(proxyorder.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(proxyorder.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(proxyorder.FieldProductID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InventoryID(); ok {
		_spec.SetField(proxyorder.FieldInventoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservationID(); ok {
		_spec.SetField(proxyorder.FieldReservationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WalletHoldID(); ok {
		_spec.SetField(proxyorder.FieldWalletHoldID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProxyAccountID(); ok {
		_spec.SetField(proxyorder.FieldProxyAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(proxyorder.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxyorder.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(proxyorder.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(proxyorder.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(proxyorder.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(proxyorder.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(proxyorder.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(proxyorder.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxyorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(proxyorder.FieldFailureReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(proxyorder.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(proxyorder.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(proxyorder.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(proxyorder.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyOrderUpdateOne is the builder for updating a single ProxyOrder entity.
type ProxyOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyOrderMutation
}

// SetUserID sets the "user_id" field.
func (_u *ProxyOrderUpdateOne) SetUserID(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableUserID(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProxyOrderUpdateOne) SetProductID(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableProductID(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetInventoryID sets the "inventory_id" field.
func (_u *ProxyOrderUpdateOne) SetInventoryID(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetInventoryID(v)
	return _u
}

// SetNillableInventoryID sets the "inventory_id" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableInventoryID(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetInventoryID(*v)
	}
	return _u
}

// SetReservationID sets the "reservation_id" field.
func (_u *ProxyOrderUpdateOne) SetReservationID(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetReservationID(v)
	return _u
}

// SetNillableReservationID sets the "reservation_id" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableReservationID(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetReservationID(*v)
	}
	return _u
}

// SetWalletHoldID sets the "wallet_hold_id" field.
func (_u *ProxyOrderUpdateOne) SetWalletHoldID(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetWalletHoldID(v)
	return _u
}

// SetNillableWalletHoldID sets the "wallet_hold_id" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableWalletHoldID(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetWalletHoldID(*v)
	}
	return _u
}

// SetProxyAccountID sets the "proxy_account_id" field.
func (_u *ProxyOrderUpdateOne) SetProxyAccountID(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetProxyAccountID(v)
	return _u
}

// SetNillableProxyAccountID sets the "proxy_account_id" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableProxyAccountID(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetProxyAccountID(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ProxyOrderUpdateOne) SetIdempotencyKey(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableIdempotencyKey(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProxyOrderUpdateOne) SetProtocol(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableProtocol(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *ProxyOrderUpdateOne) SetDurationDays(v int) *ProxyOrderUpdateOne {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableDurationDays(v *int) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *ProxyOrderUpdateOne) AddDurationDays(v int) *ProxyOrderUpdateOne {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *ProxyOrderUpdateOne) SetQuantity(v int) *ProxyOrderUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableQuantity(v *int) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *ProxyOrderUpdateOne) AddQuantity(v int) *ProxyOrderUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *ProxyOrderUpdateOne) SetAmountCents(v int64) *ProxyOrderUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableAmountCents(v *int64) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *ProxyOrderUpdateOne) AddAmountCents(v int64) *ProxyOrderUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyOrderUpdateOne) SetStatus(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableStatus(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *ProxyOrderUpdateOne) SetFailureReason(v string) *ProxyOrderUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableFailureReason(v *string) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyOrderUpdateOne) SetUpdatedAt(v time.Time) *ProxyOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *ProxyOrderUpdateOne) SetDeliveredAt(v time.Time) *ProxyOrderUpdateOne {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableDeliveredAt(v *time.Time) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *ProxyOrderUpdateOne) ClearDeliveredAt() *ProxyOrderUpdateOne {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ProxyOrderUpdateOne) SetExpiresAt(v time.Time) *ProxyOrderUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProxyOrderUpdateOne) SetNillableExpiresAt(v *time.Time) *ProxyOrderUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ProxyOrderUpdateOne) ClearExpiresAt() *ProxyOrderUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the ProxyOrderMutation object of the builder.
func (_u *ProxyOrderUpdateOne) Mutation() *ProxyOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxyOrderUpdate builder.
func (_u *ProxyOrderUpdateOne) Where(ps ...predicate.ProxyOrder) *ProxyOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyOrderUpdateOne) Select(field string, fields ...string) *ProxyOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyOrder entity.
func (_u *ProxyOrderUpdateOne) Save(ctx context.Context) (*ProxyOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyOrderUpdateOne) SaveX(ctx context.Context) *ProxyOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ProxyOrderUpdateOne) sqlSave(ctx context.Context) (_node *ProxyOrder, err error) {
	_spec := sqlgraph.NewUpdateSpec(proxyorder.Table, proxyorder.Columns, sqlgraph.NewFieldSpec(proxyorder.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyorder.FieldID)
		for _, f := range fields {
			if !proxyorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxyorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(proxyorder.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(proxyorder.FieldProductID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InventoryID(); ok {
		_spec.SetField(proxyorder.FieldInventoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReservationID(); ok {
		_spec.SetField(proxyorder.FieldReservationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WalletHoldID(); ok {
		_spec.SetField(proxyorder.FieldWalletHoldID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProxyAccountID(); ok {
		_spec.SetField(proxyorder.FieldProxyAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(proxyorder.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxyorder.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(proxyorder.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(proxyorder.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(proxyorder.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(proxyorder.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(proxyorder.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(proxyorder.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxyorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(proxyorder.FieldFailureReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(proxyorder.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(proxyorder.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(proxyorder.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(proxyorder.FieldExpiresAt, field.TypeTime)
	}
	_node = &ProxyOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
