// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/ratepolicy"
)

// RatePolicyCreate is the builder for creating a RatePolicy entity.
type RatePolicyCreate struct {
	config
	mutation *RatePolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *RatePolicyCreate) SetName(v string) *RatePolicyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEgressLimitBps sets the "egress_limit_bps" field.
func (_c *RatePolicyCreate) SetEgressLimitBps(v uint64) *RatePolicyCreate {
	_c.mutation.SetEgressLimitBps(v)
	return _c
}

// SetNillableEgressLimitBps sets the "egress_limit_bps" field if the given value is not nil.
func (_c *RatePolicyCreate) SetNillableEgressLimitBps(v *uint64) *RatePolicyCreate {
	if v != nil {
		_c.SetEgressLimitBps(*v)
	}
	return _c
}

// SetIngressLimitBps sets the "ingress_limit_bps" field.
func (_c *RatePolicyCreate) SetIngressLimitBps(v uint64) *RatePolicyCreate {
	_c.mutation.SetIngressLimitBps(v)
	return _c
}

// SetNillableIngressLimitBps sets the "ingress_limit_bps" field if the given value is not nil.
func (_c *RatePolicyCreate) SetNillableIngressLimitBps(v *uint64) *RatePolicyCreate {
	if v != nil {
		_c.SetIngressLimitBps(*v)
	}
	return _c
}

// SetMaxConnections sets the "max_connections" field.
func (_c *RatePolicyCreate) SetMaxConnections(v uint32) *RatePolicyCreate {
	_c.mutation.SetMaxConnections(v)
	return _c
}

// SetNillableMaxConnections sets the "max_connections" field if the given value is not nil.
func (_c *RatePolicyCreate) SetNillableMaxConnections(v *uint32) *RatePolicyCreate {
	if v != nil {
		_c.SetMaxConnections(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RatePolicyCreate) SetCreatedAt(v time.Time) *RatePolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RatePolicyCreate) SetNillableCreatedAt(v *time.Time) *RatePolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RatePolicyCreate) SetUpdatedAt(v time.Time) *RatePolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RatePolicyCreate) SetNillableUpdatedAt(v *time.Time) *RatePolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RatePolicyCreate) SetID(v string) *RatePolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RatePolicyMutation object of the builder.
func (_c *RatePolicyCreate) Mutation() *RatePolicyMutation {
	return _c.mutation
}

// Save creates the RatePolicy in the database.
func (_c *RatePolicyCreate) Save(ctx context.Context) (*RatePolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RatePolicyCreate) SaveX(ctx context.Context) *RatePolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RatePolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RatePolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RatePolicyCreate) defaults() {
	if _, ok := _c.mutation.EgressLimitBps(); !ok {
		v := ratepolicy.DefaultEgressLimitBps
		_c.mutation.SetEgressLimitBps(v)
	}
	if _, ok := _c.mutation.IngressLimitBps(); !ok {
		v := ratepolicy.DefaultIngressLimitBps
		_c.mutation.SetIngressLimitBps(v)
	}
	if _, ok := _c.mutation.MaxConnections(); !ok {
		v := ratepolicy.DefaultMaxConnections
		_c.mutation.SetMaxConnections(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ratepolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ratepolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RatePolicyCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RatePolicy.name"`)}
	}
	if _, ok := _c.mutation.EgressLimitBps(); !ok {
		return &ValidationError{Name: "egress_limit_bps", err: errors.New(`ent: missing required field "RatePolicy.egress_limit_bps"`)}
	}
	if _, ok := _c.mutation.IngressLimitBps(); !ok {
		return &ValidationError{Name: "ingress_limit_bps", err: errors.New(`ent: missing required field "RatePolicy.ingress_limit_bps"`)}
	}
	if _, ok := _c.mutation.MaxConnections(); !ok {
		return &ValidationError{Name: "max_connections", err: errors.New(`ent: missing required field "RatePolicy.max_connections"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RatePolicy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RatePolicy.updated_at"`)}
	}
	return nil
}

func (_c *RatePolicyCreate) sqlSave(ctx context.Context) (*RatePolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RatePolicy.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RatePolicyCreate) createSpec() (*RatePolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &RatePolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ratepolicy.Table, sqlgraph.NewFieldSpec(ratepolicy.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ratepolicy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.EgressLimitBps(); ok {
		_spec.SetField(ratepolicy.FieldEgressLimitBps, field.TypeUint64, value)
		_node.EgressLimitBps = value
	}
	if value, ok := _c.mutation.IngressLimitBps(); ok {
		_spec.SetField(ratepolicy.FieldIngressLimitBps, field.TypeUint64, value)
		_node.IngressLimitBps = value
	}
	if value, ok := _c.mutation.MaxConnections(); ok {
		_spec.SetField(ratepolicy.FieldMaxConnections, field.TypeUint32, value)
		_node.MaxConnections = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ratepolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ratepolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RatePolicy.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RatePolicyUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *RatePolicyCreate) OnConflict(opts ...sql.ConflictOption) *RatePolicyUpsertOne {
	_c.conflict = opts
	return &RatePolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RatePolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RatePolicyCreate) OnConflictColumns(columns ...string) *RatePolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RatePolicyUpsertOne{
		create: _c,
	}
}

type (
	// RatePolicyUpsertOne is the builder for "upsert"-ing
	//  one RatePolicy node.
	RatePolicyUpsertOne struct {
		create *RatePolicyCreate
	}

	// RatePolicyUpsert is the "OnConflict" setter.
	RatePolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *RatePolicyUpsert) SetName(v string) *RatePolicyUpsert {
	u.Set(ratepolicy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RatePolicyUpsert) UpdateName() *RatePolicyUpsert {
	u.SetExcluded(ratepolicy.FieldName)
	return u
}

// SetEgressLimitBps sets the "egress_limit_bps" field.
func (u *RatePolicyUpsert) SetEgressLimitBps(v uint64) *RatePolicyUpsert {
	u.Set(ratepolicy.FieldEgressLimitBps, v)
	return u
}

// UpdateEgressLimitBps sets the "egress_limit_bps" field to the value that was provided on create.
func (u *RatePolicyUpsert) UpdateEgressLimitBps() *RatePolicyUpsert {
	u.SetExcluded(ratepolicy.FieldEgressLimitBps)
	return u
}

// AddEgressLimitBps adds v to the "egress_limit_bps" field.
func (u *RatePolicyUpsert) AddEgressLimitBps(v uint64) *RatePolicyUpsert {
	u.Add(ratepolicy.FieldEgressLimitBps, v)
	return u
}

// SetIngressLimitBps sets the "ingress_limit_bps" field.
func (u *RatePolicyUpsert) SetIngressLimitBps(v uint64) *RatePolicyUpsert {
	u.Set(ratepolicy.FieldIngressLimitBps, v)
	return u
}

// UpdateIngressLimitBps sets the "ingress_limit_bps" field to the value that was provided on create.
func (u *RatePolicyUpsert) UpdateIngressLimitBps() *RatePolicyUpsert {
	u.SetExcluded(ratepolicy.FieldIngressLimitBps)
	return u
}

// AddIngressLimitBps adds v to the "ingress_limit_bps" field.
func (u *RatePolicyUpsert) AddIngressLimitBps(v uint64) *RatePolicyUpsert {
	u.Add(ratepolicy.FieldIngressLimitBps, v)
	return u
}

// SetMaxConnections sets the "max_connections" field.
func (u *RatePolicyUpsert) SetMaxConnections(v uint32) *RatePolicyUpsert {
	u.Set(ratepolicy.FieldMaxConnections, v)
	return u
}

// UpdateMaxConnections sets the "max_connections" field to the value that was provided on create.
func (u *RatePolicyUpsert) UpdateMaxConnections() *RatePolicyUpsert {
	u.SetExcluded(ratepolicy.FieldMaxConnections)
	return u
}

// AddMaxConnections adds v to the "max_connections" field.
func (u *RatePolicyUpsert) AddMaxConnections(v uint32) *RatePolicyUpsert {
	u.Add(ratepolicy.FieldMaxConnections, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RatePolicyUpsert) SetUpdatedAt(v time.Time) *RatePolicyUpsert {
	u.Set(ratepolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RatePolicyUpsert) UpdateUpdatedAt() *RatePolicyUpsert {
	u.SetExcluded(ratepolicy.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RatePolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ratepolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RatePolicyUpsertOne) UpdateNewValues() *RatePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ratepolicy.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ratepolicy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RatePolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RatePolicyUpsertOne) Ignore() *RatePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RatePolicyUpsertOne) DoNothing() *RatePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RatePolicyCreate.OnConflict
// documentation for more info.
func (u *RatePolicyUpsertOne) Update(set func(*RatePolicyUpsert)) *RatePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RatePolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RatePolicyUpsertOne) SetName(v string) *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RatePolicyUpsertOne) UpdateName() *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateName()
	})
}

// SetEgressLimitBps sets the "egress_limit_bps" field.
func (u *RatePolicyUpsertOne) SetEgressLimitBps(v uint64) *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetEgressLimitBps(v)
	})
}

// AddEgressLimitBps adds v to the "egress_limit_bps" field.
func (u *RatePolicyUpsertOne) AddEgressLimitBps(v uint64) *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.AddEgressLimitBps(v)
	})
}

// UpdateEgressLimitBps sets the "egress_limit_bps" field to the value that was provided on create.
func (u *RatePolicyUpsertOne) UpdateEgressLimitBps() *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateEgressLimitBps()
	})
}

// SetIngressLimitBps sets the "ingress_limit_bps" field.
func (u *RatePolicyUpsertOne) SetIngressLimitBps(v uint64) *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetIngressLimitBps(v)
	})
}

// AddIngressLimitBps adds v to the "ingress_limit_bps" field.
func (u *RatePolicyUpsertOne) AddIngressLimitBps(v uint64) *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.AddIngressLimitBps(v)
	})
}

// UpdateIngressLimitBps sets the "ingress_limit_bps" field to the value that was provided on create.
func (u *RatePolicyUpsertOne) UpdateIngressLimitBps() *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateIngressLimitBps()
	})
}

// SetMaxConnections sets the "max_connections" field.
func (u *RatePolicyUpsertOne) SetMaxConnections(v uint32) *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetMaxConnections(v)
	})
}

// AddMaxConnections adds v to the "max_connections" field.
func (u *RatePolicyUpsertOne) AddMaxConnections(v uint32) *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.AddMaxConnections(v)
	})
}

// UpdateMaxConnections sets the "max_connections" field to the value that was provided on create.
func (u *RatePolicyUpsertOne) UpdateMaxConnections() *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateMaxConnections()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RatePolicyUpsertOne) SetUpdatedAt(v time.Time) *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RatePolicyUpsertOne) UpdateUpdatedAt() *RatePolicyUpsertOne {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RatePolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RatePolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RatePolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RatePolicyUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RatePolicyUpsertOne.ID is not supported by MySQL driver. Use RatePolicyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RatePolicyUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RatePolicyCreateBulk is the builder for creating many RatePolicy entities in bulk.
type RatePolicyCreateBulk struct {
	config
	err      error
	builders []*RatePolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the RatePolicy entities in the database.
func (_c *RatePolicyCreateBulk) Save(ctx context.Context) ([]*RatePolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RatePolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RatePolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RatePolicyCreateBulk) SaveX(ctx context.Context) []*RatePolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RatePolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RatePolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RatePolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RatePolicyUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *RatePolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *RatePolicyUpsertBulk {
	_c.conflict = opts
	return &RatePolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RatePolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RatePolicyCreateBulk) OnConflictColumns(columns ...string) *RatePolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RatePolicyUpsertBulk{
		create: _c,
	}
}

// RatePolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of RatePolicy nodes.
type RatePolicyUpsertBulk struct {
	create *RatePolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RatePolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ratepolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RatePolicyUpsertBulk) UpdateNewValues() *RatePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ratepolicy.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ratepolicy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RatePolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RatePolicyUpsertBulk) Ignore() *RatePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RatePolicyUpsertBulk) DoNothing() *RatePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RatePolicyCreateBulk.OnConflict
// documentation for more info.
func (u *RatePolicyUpsertBulk) Update(set func(*RatePolicyUpsert)) *RatePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RatePolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RatePolicyUpsertBulk) SetName(v string) *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RatePolicyUpsertBulk) UpdateName() *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateName()
	})
}

// SetEgressLimitBps sets the "egress_limit_bps" field.
func (u *RatePolicyUpsertBulk) SetEgressLimitBps(v uint64) *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetEgressLimitBps(v)
	})
}

// AddEgressLimitBps adds v to the "egress_limit_bps" field.
func (u *RatePolicyUpsertBulk) AddEgressLimitBps(v uint64) *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.AddEgressLimitBps(v)
	})
}

// UpdateEgressLimitBps sets the "egress_limit_bps" field to the value that was provided on create.
func (u *RatePolicyUpsertBulk) UpdateEgressLimitBps() *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateEgressLimitBps()
	})
}

// SetIngressLimitBps sets the "ingress_limit_bps" field.
func (u *RatePolicyUpsertBulk) SetIngressLimitBps(v uint64) *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetIngressLimitBps(v)
	})
}

// AddIngressLimitBps adds v to the "ingress_limit_bps" field.
func (u *RatePolicyUpsertBulk) AddIngressLimitBps(v uint64) *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.AddIngressLimitBps(v)
	})
}

// UpdateIngressLimitBps sets the "ingress_limit_bps" field to the value that was provided on create.
func (u *RatePolicyUpsertBulk) UpdateIngressLimitBps() *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateIngressLimitBps()
	})
}

// SetMaxConnections sets the "max_connections" field.
func (u *RatePolicyUpsertBulk) SetMaxConnections(v uint32) *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetMaxConnections(v)
	})
}

// AddMaxConnections adds v to the "max_connections" field.
func (u *RatePolicyUpsertBulk) AddMaxConnections(v uint32) *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.AddMaxConnections(v)
	})
}

// UpdateMaxConnections sets the "max_connections" field to the value that was provided on create.
func (u *RatePolicyUpsertBulk) UpdateMaxConnections() *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateMaxConnections()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RatePolicyUpsertBulk) SetUpdatedAt(v time.Time) *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RatePolicyUpsertBulk) UpdateUpdatedAt() *RatePolicyUpsertBulk {
	return u.Update(func(s *RatePolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RatePolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RatePolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RatePolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RatePolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
