// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/predicate"
	"github.com/rayip/rayip/services/api/ent/runtimechangelog"
)

// RuntimeChangeLogUpdate is the builder for updating RuntimeChangeLog entities.
type RuntimeChangeLogUpdate struct {
	config
	hooks    []Hook
	mutation *RuntimeChangeLogMutation
}

// Where appends a list predicates to the RuntimeChangeLogUpdate builder.
func (_u *RuntimeChangeLogUpdate) Where(ps ...predicate.RuntimeChangeLog) *RuntimeChangeLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *RuntimeChangeLogUpdate) SetNodeID(v string) *RuntimeChangeLogUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdate) SetNillableNodeID(v *string) *RuntimeChangeLogUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *RuntimeChangeLogUpdate) SetSeq(v uint64) *RuntimeChangeLogUpdate {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdate) SetNillableSeq(v *uint64) *RuntimeChangeLogUpdate {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *RuntimeChangeLogUpdate) AddSeq(v int64) *RuntimeChangeLogUpdate {
	_u.mutation.AddSeq(v)
	return _u
}

// SetResourceName sets the "resource_name" field.
func (_u *RuntimeChangeLogUpdate) SetResourceName(v string) *RuntimeChangeLogUpdate {
	_u.mutation.SetResourceName(v)
	return _u
}

// SetNillableResourceName sets the "resource_name" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdate) SetNillableResourceName(v *string) *RuntimeChangeLogUpdate {
	if v != nil {
		_u.SetResourceName(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *RuntimeChangeLogUpdate) SetAction(v string) *RuntimeChangeLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdate) SetNillableAction(v *string) *RuntimeChangeLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *RuntimeChangeLogUpdate) SetRevision(v uint64) *RuntimeChangeLogUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdate) SetNillableRevision(v *uint64) *RuntimeChangeLogUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *RuntimeChangeLogUpdate) AddRevision(v int64) *RuntimeChangeLogUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// Mutation returns the RuntimeChangeLogMutation object of the builder.
func (_u *RuntimeChangeLogUpdate) Mutation() *RuntimeChangeLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RuntimeChangeLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuntimeChangeLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RuntimeChangeLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuntimeChangeLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RuntimeChangeLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(runtimechangelog.Table, runtimechangelog.Columns, sqlgraph.NewFieldSpec(runtimechangelog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(runtimechangelog.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(runtimechangelog.FieldSeq, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(runtimechangelog.FieldSeq, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ResourceName(); ok {
		_spec.SetField(runtimechangelog.FieldResourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(runtimechangelog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(runtimechangelog.FieldRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(runtimechangelog.FieldRevision, field.TypeUint64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runtimechangelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RuntimeChangeLogUpdateOne is the builder for updating a single RuntimeChangeLog entity.
type RuntimeChangeLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RuntimeChangeLogMutation
}

// SetNodeID sets the "node_id" field.
func (_u *RuntimeChangeLogUpdateOne) SetNodeID(v string) *RuntimeChangeLogUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdateOne) SetNillableNodeID(v *string) *RuntimeChangeLogUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetSeq sets the "seq" field.
func (_u *RuntimeChangeLogUpdateOne) SetSeq(v uint64) *RuntimeChangeLogUpdateOne {
	_u.mutation.ResetSeq()
	_u.mutation.SetSeq(v)
	return _u
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdateOne) SetNillableSeq(v *uint64) *RuntimeChangeLogUpdateOne {
	if v != nil {
		_u.SetSeq(*v)
	}
	return _u
}

// AddSeq adds value to the "seq" field.
func (_u *RuntimeChangeLogUpdateOne) AddSeq(v int64) *RuntimeChangeLogUpdateOne {
	_u.mutation.AddSeq(v)
	return _u
}

// SetResourceName sets the "resource_name" field.
func (_u *RuntimeChangeLogUpdateOne) SetResourceName(v string) *RuntimeChangeLogUpdateOne {
	_u.mutation.SetResourceName(v)
	return _u
}

// SetNillableResourceName sets the "resource_name" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdateOne) SetNillableResourceName(v *string) *RuntimeChangeLogUpdateOne {
	if v != nil {
		_u.SetResourceName(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *RuntimeChangeLogUpdateOne) SetAction(v string) *RuntimeChangeLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdateOne) SetNillableAction(v *string) *RuntimeChangeLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *RuntimeChangeLogUpdateOne) SetRevision(v uint64) *RuntimeChangeLogUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *RuntimeChangeLogUpdateOne) SetNillableRevision(v *uint64) *RuntimeChangeLogUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *RuntimeChangeLogUpdateOne) AddRevision(v int64) *RuntimeChangeLogUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// Mutation returns the RuntimeChangeLogMutation object of the builder.
func (_u *RuntimeChangeLogUpdateOne) Mutation() *RuntimeChangeLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RuntimeChangeLogUpdate builder.
func (_u *RuntimeChangeLogUpdateOne) Where(ps ...predicate.RuntimeChangeLog) *RuntimeChangeLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RuntimeChangeLogUpdateOne) Select(field string, fields ...string) *RuntimeChangeLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RuntimeChangeLog entity.
func (_u *RuntimeChangeLogUpdateOne) Save(ctx context.Context) (*RuntimeChangeLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuntimeChangeLogUpdateOne) SaveX(ctx context.Context) *RuntimeChangeLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RuntimeChangeLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuntimeChangeLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RuntimeChangeLogUpdateOne) sqlSave(ctx context.Context) (_node *RuntimeChangeLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(runtimechangelog.Table, runtimechangelog.Columns, sqlgraph.NewFieldSpec(runtimechangelog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RuntimeChangeLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runtimechangelog.FieldID)
		for _, f := range fields {
			if !runtimechangelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runtimechangelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(runtimechangelog.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Seq(); ok {
		_spec.SetField(runtimechangelog.FieldSeq, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSeq(); ok {
		_spec.AddField(runtimechangelog.FieldSeq, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ResourceName(); ok {
		_spec.SetField(runtimechangelog.FieldResourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(runtimechangelog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(runtimechangelog.FieldRevision, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(runtimechangelog.FieldRevision, field.TypeUint64, value)
	}
	_node = &RuntimeChangeLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runtimechangelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
