// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/predicate"
	"github.com/rayip/rayip/services/api/ent/runtimelabaccount"
)

// RuntimeLabAccountDelete is the builder for deleting a RuntimeLabAccount entity.
type RuntimeLabAccountDelete struct {
	config
	hooks    []Hook
	mutation *RuntimeLabAccountMutation
}

// Where appends a list predicates to the RuntimeLabAccountDelete builder.
func (_d *RuntimeLabAccountDelete) Where(ps ...predicate.RuntimeLabAccount) *RuntimeLabAccountDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RuntimeLabAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RuntimeLabAccountDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RuntimeLabAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(runtimelabaccount.Table, sqlgraph.NewFieldSpec(runtimelabaccount.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RuntimeLabAccountDeleteOne is the builder for deleting a single RuntimeLabAccount entity.
type RuntimeLabAccountDeleteOne struct {
	_d *RuntimeLabAccountDelete
}

// Where appends a list predicates to the RuntimeLabAccountDelete builder.
func (_d *RuntimeLabAccountDeleteOne) Where(ps ...predicate.RuntimeLabAccount) *RuntimeLabAccountDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RuntimeLabAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{runtimelabaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RuntimeLabAccountDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
