// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/rayip/rayip/services/api/ent/predicate"
	"github.com/rayip/rayip/services/api/ent/runtimeapplyresult"
)

// RuntimeApplyResultDelete is the builder for deleting a RuntimeApplyResult entity.
type RuntimeApplyResultDelete struct {
	config
	hooks    []Hook
	mutation *RuntimeApplyResultMutation
}

// Where appends a list predicates to the RuntimeApplyResultDelete builder.
func (_d *RuntimeApplyResultDelete) Where(ps ...predicate.RuntimeApplyResult) *RuntimeApplyResultDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RuntimeApplyResultDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RuntimeApplyResultDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RuntimeApplyResultDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(runtimeapplyresult.Table, sqlgraph.NewFieldSpec(runtimeapplyresult.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RuntimeApplyResultDeleteOne is the builder for deleting a single RuntimeApplyResult entity.
type RuntimeApplyResultDeleteOne struct {
	_d *RuntimeApplyResultDelete
}

// Where appends a list predicates to the RuntimeApplyResultDelete builder.
func (_d *RuntimeApplyResultDeleteOne) Where(ps ...predicate.RuntimeApplyResult) *RuntimeApplyResultDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RuntimeApplyResultDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{runtimeapplyresult.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RuntimeApplyResultDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
