// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/wallethold"
)

// WalletHold is the model entity for the WalletHold schema.
type WalletHold struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// WalletID holds the value of the "wallet_id" field.
	WalletID string `json:"wallet_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID string `json:"order_id,omitempty"`
	// AmountCents holds the value of the "amount_cents" field.
	AmountCents int64 `json:"amount_cents,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WalletHold) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wallethold.FieldAmountCents:
			values[i] = new(sql.NullInt64)
		case wallethold.FieldID, wallethold.FieldWalletID, wallethold.FieldUserID, wallethold.FieldOrderID, wallethold.FieldStatus:
			values[i] = new(sql.NullString)
		case wallethold.FieldCreatedAt, wallethold.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WalletHold fields.
func (_m *WalletHold) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wallethold.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case wallethold.FieldWalletID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_id", values[i])
			} else if value.Valid {
				_m.WalletID = value.String
			}
		case wallethold.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case wallethold.FieldOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.String
			}
		case wallethold.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				_m.AmountCents = value.Int64
			}
		case wallethold.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case wallethold.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case wallethold.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WalletHold.
// This includes values selected through modifiers, order, etc.
func (_m *WalletHold) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WalletHold.
// Note that you need to call WalletHold.Unwrap() before calling this method if this WalletHold
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WalletHold) Update() *WalletHoldUpdateOne {
	return NewWalletHoldClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WalletHold entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WalletHold) Unwrap() *WalletHold {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WalletHold is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WalletHold) String() string {
	var builder strings.Builder
	builder.WriteString("WalletHold(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("wallet_id=")
	builder.WriteString(_m.WalletID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(_m.OrderID)
	builder.WriteString(", ")
	builder.WriteString("amount_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCents))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WalletHolds is a parsable slice of WalletHold.
type WalletHolds []*WalletHold
