// Code generated by ent, DO NOT EDIT.

package nodeagentsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContainsFold(FieldID, id))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldNodeID, v))
}

// APIInstanceID applies equality check predicate on the "api_instance_id" field. It's identical to APIInstanceIDEQ.
func APIInstanceID(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldAPIInstanceID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldStatus, v))
}

// BundleVersion applies equality check predicate on the "bundle_version" field. It's identical to BundleVersionEQ.
func BundleVersion(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldBundleVersion, v))
}

// ConnectedAt applies equality check predicate on the "connected_at" field. It's identical to ConnectedAtEQ.
func ConnectedAt(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldConnectedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContainsFold(FieldNodeID, v))
}

// APIInstanceIDEQ applies the EQ predicate on the "api_instance_id" field.
func APIInstanceIDEQ(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldAPIInstanceID, v))
}

// APIInstanceIDNEQ applies the NEQ predicate on the "api_instance_id" field.
func APIInstanceIDNEQ(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldAPIInstanceID, v))
}

// APIInstanceIDIn applies the In predicate on the "api_instance_id" field.
func APIInstanceIDIn(vs ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldAPIInstanceID, vs...))
}

// APIInstanceIDNotIn applies the NotIn predicate on the "api_instance_id" field.
func APIInstanceIDNotIn(vs ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldAPIInstanceID, vs...))
}

// APIInstanceIDGT applies the GT predicate on the "api_instance_id" field.
func APIInstanceIDGT(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldAPIInstanceID, v))
}

// APIInstanceIDGTE applies the GTE predicate on the "api_instance_id" field.
func APIInstanceIDGTE(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldAPIInstanceID, v))
}

// APIInstanceIDLT applies the LT predicate on the "api_instance_id" field.
func APIInstanceIDLT(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldAPIInstanceID, v))
}

// APIInstanceIDLTE applies the LTE predicate on the "api_instance_id" field.
func APIInstanceIDLTE(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldAPIInstanceID, v))
}

// APIInstanceIDContains applies the Contains predicate on the "api_instance_id" field.
func APIInstanceIDContains(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContains(FieldAPIInstanceID, v))
}

// APIInstanceIDHasPrefix applies the HasPrefix predicate on the "api_instance_id" field.
func APIInstanceIDHasPrefix(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldHasPrefix(FieldAPIInstanceID, v))
}

// APIInstanceIDHasSuffix applies the HasSuffix predicate on the "api_instance_id" field.
func APIInstanceIDHasSuffix(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldHasSuffix(FieldAPIInstanceID, v))
}

// APIInstanceIDEqualFold applies the EqualFold predicate on the "api_instance_id" field.
func APIInstanceIDEqualFold(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEqualFold(FieldAPIInstanceID, v))
}

// APIInstanceIDContainsFold applies the ContainsFold predicate on the "api_instance_id" field.
func APIInstanceIDContainsFold(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContainsFold(FieldAPIInstanceID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContainsFold(FieldStatus, v))
}

// BundleVersionEQ applies the EQ predicate on the "bundle_version" field.
func BundleVersionEQ(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldBundleVersion, v))
}

// BundleVersionNEQ applies the NEQ predicate on the "bundle_version" field.
func BundleVersionNEQ(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldBundleVersion, v))
}

// BundleVersionIn applies the In predicate on the "bundle_version" field.
func BundleVersionIn(vs ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldBundleVersion, vs...))
}

// BundleVersionNotIn applies the NotIn predicate on the "bundle_version" field.
func BundleVersionNotIn(vs ...string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldBundleVersion, vs...))
}

// BundleVersionGT applies the GT predicate on the "bundle_version" field.
func BundleVersionGT(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldBundleVersion, v))
}

// BundleVersionGTE applies the GTE predicate on the "bundle_version" field.
func BundleVersionGTE(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldBundleVersion, v))
}

// BundleVersionLT applies the LT predicate on the "bundle_version" field.
func BundleVersionLT(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldBundleVersion, v))
}

// BundleVersionLTE applies the LTE predicate on the "bundle_version" field.
func BundleVersionLTE(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldBundleVersion, v))
}

// BundleVersionContains applies the Contains predicate on the "bundle_version" field.
func BundleVersionContains(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContains(FieldBundleVersion, v))
}

// BundleVersionHasPrefix applies the HasPrefix predicate on the "bundle_version" field.
func BundleVersionHasPrefix(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldHasPrefix(FieldBundleVersion, v))
}

// BundleVersionHasSuffix applies the HasSuffix predicate on the "bundle_version" field.
func BundleVersionHasSuffix(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldHasSuffix(FieldBundleVersion, v))
}

// BundleVersionEqualFold applies the EqualFold predicate on the "bundle_version" field.
func BundleVersionEqualFold(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEqualFold(FieldBundleVersion, v))
}

// BundleVersionContainsFold applies the ContainsFold predicate on the "bundle_version" field.
func BundleVersionContainsFold(v string) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldContainsFold(FieldBundleVersion, v))
}

// ConnectedAtEQ applies the EQ predicate on the "connected_at" field.
func ConnectedAtEQ(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldConnectedAt, v))
}

// ConnectedAtNEQ applies the NEQ predicate on the "connected_at" field.
func ConnectedAtNEQ(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldConnectedAt, v))
}

// ConnectedAtIn applies the In predicate on the "connected_at" field.
func ConnectedAtIn(vs ...time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldConnectedAt, vs...))
}

// ConnectedAtNotIn applies the NotIn predicate on the "connected_at" field.
func ConnectedAtNotIn(vs ...time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldConnectedAt, vs...))
}

// ConnectedAtGT applies the GT predicate on the "connected_at" field.
func ConnectedAtGT(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldConnectedAt, v))
}

// ConnectedAtGTE applies the GTE predicate on the "connected_at" field.
func ConnectedAtGTE(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldConnectedAt, v))
}

// ConnectedAtLT applies the LT predicate on the "connected_at" field.
func ConnectedAtLT(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldConnectedAt, v))
}

// ConnectedAtLTE applies the LTE predicate on the "connected_at" field.
func ConnectedAtLTE(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldConnectedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NodeAgentSession) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NodeAgentSession) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NodeAgentSession) predicate.NodeAgentSession {
	return predicate.NodeAgentSession(sql.NotPredicates(p))
}
