// Code generated by ent, DO NOT EDIT.

package wallethold

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContainsFold(FieldID, id))
}

// WalletID applies equality check predicate on the "wallet_id" field. It's identical to WalletIDEQ.
func WalletID(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldWalletID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldUserID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldOrderID, v))
}

// AmountCents applies equality check predicate on the "amount_cents" field. It's identical to AmountCentsEQ.
func AmountCents(v int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldAmountCents, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldUpdatedAt, v))
}

// WalletIDEQ applies the EQ predicate on the "wallet_id" field.
func WalletIDEQ(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldWalletID, v))
}

// WalletIDNEQ applies the NEQ predicate on the "wallet_id" field.
func WalletIDNEQ(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNEQ(FieldWalletID, v))
}

// WalletIDIn applies the In predicate on the "wallet_id" field.
func WalletIDIn(vs ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldIn(FieldWalletID, vs...))
}

// WalletIDNotIn applies the NotIn predicate on the "wallet_id" field.
func WalletIDNotIn(vs ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNotIn(FieldWalletID, vs...))
}

// WalletIDGT applies the GT predicate on the "wallet_id" field.
func WalletIDGT(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGT(FieldWalletID, v))
}

// WalletIDGTE applies the GTE predicate on the "wallet_id" field.
func WalletIDGTE(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGTE(FieldWalletID, v))
}

// WalletIDLT applies the LT predicate on the "wallet_id" field.
func WalletIDLT(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLT(FieldWalletID, v))
}

// WalletIDLTE applies the LTE predicate on the "wallet_id" field.
func WalletIDLTE(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLTE(FieldWalletID, v))
}

// WalletIDContains applies the Contains predicate on the "wallet_id" field.
func WalletIDContains(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContains(FieldWalletID, v))
}

// WalletIDHasPrefix applies the HasPrefix predicate on the "wallet_id" field.
func WalletIDHasPrefix(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldHasPrefix(FieldWalletID, v))
}

// WalletIDHasSuffix applies the HasSuffix predicate on the "wallet_id" field.
func WalletIDHasSuffix(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldHasSuffix(FieldWalletID, v))
}

// WalletIDEqualFold applies the EqualFold predicate on the "wallet_id" field.
func WalletIDEqualFold(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEqualFold(FieldWalletID, v))
}

// WalletIDContainsFold applies the ContainsFold predicate on the "wallet_id" field.
func WalletIDContainsFold(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContainsFold(FieldWalletID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContainsFold(FieldUserID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContainsFold(FieldOrderID, v))
}

// AmountCentsEQ applies the EQ predicate on the "amount_cents" field.
func AmountCentsEQ(v int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldAmountCents, v))
}

// AmountCentsNEQ applies the NEQ predicate on the "amount_cents" field.
func AmountCentsNEQ(v int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNEQ(FieldAmountCents, v))
}

// AmountCentsIn applies the In predicate on the "amount_cents" field.
func AmountCentsIn(vs ...int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldIn(FieldAmountCents, vs...))
}

// AmountCentsNotIn applies the NotIn predicate on the "amount_cents" field.
func AmountCentsNotIn(vs ...int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNotIn(FieldAmountCents, vs...))
}

// AmountCentsGT applies the GT predicate on the "amount_cents" field.
func AmountCentsGT(v int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGT(FieldAmountCents, v))
}

// AmountCentsGTE applies the GTE predicate on the "amount_cents" field.
func AmountCentsGTE(v int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGTE(FieldAmountCents, v))
}

// AmountCentsLT applies the LT predicate on the "amount_cents" field.
func AmountCentsLT(v int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLT(FieldAmountCents, v))
}

// AmountCentsLTE applies the LTE predicate on the "amount_cents" field.
func AmountCentsLTE(v int64) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLTE(FieldAmountCents, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WalletHold {
	return predicate.WalletHold(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WalletHold) predicate.WalletHold {
	return predicate.WalletHold(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WalletHold) predicate.WalletHold {
	return predicate.WalletHold(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WalletHold) predicate.WalletHold {
	return predicate.WalletHold(sql.NotPredicates(p))
}
