// Code generated by ent, DO NOT EDIT.

package wallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the wallet type in the database.
	Label = "wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldBalanceCents holds the string denoting the balance_cents field in the database.
	FieldBalanceCents = "balance_cents"
	// FieldHeldCents holds the string denoting the held_cents field in the database.
	FieldHeldCents = "held_cents"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the wallet in the database.
	Table = "wallets"
)

// Columns holds all SQL columns for wallet fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldBalanceCents,
	FieldHeldCents,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBalanceCents holds the default value on creation for the "balance_cents" field.
	DefaultBalanceCents int64
	// DefaultHeldCents holds the default value on creation for the "held_cents" field.
	DefaultHeldCents int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Wallet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByBalanceCents orders the results by the balance_cents field.
func ByBalanceCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceCents, opts...).ToFunc()
}

// ByHeldCents orders the results by the held_cents field.
func ByHeldCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeldCents, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
