// Code generated by ent, DO NOT EDIT.

package proxyaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the proxyaccount type in the database.
	Label = "proxy_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldInventoryID holds the string denoting the inventory_id field in the database.
	FieldInventoryID = "inventory_id"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldListenIP holds the string denoting the listen_ip field in the database.
	FieldListenIP = "listen_ip"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldConnectionURI holds the string denoting the connection_uri field in the database.
	FieldConnectionURI = "connection_uri"
	// FieldRuntimeEmail holds the string denoting the runtime_email field in the database.
	FieldRuntimeEmail = "runtime_email"
	// FieldEgressLimitBps holds the string denoting the egress_limit_bps field in the database.
	FieldEgressLimitBps = "egress_limit_bps"
	// FieldIngressLimitBps holds the string denoting the ingress_limit_bps field in the database.
	FieldIngressLimitBps = "ingress_limit_bps"
	// FieldMaxConnections holds the string denoting the max_connections field in the database.
	FieldMaxConnections = "max_connections"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLifecycleStatus holds the string denoting the lifecycle_status field in the database.
	FieldLifecycleStatus = "lifecycle_status"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the proxyaccount in the database.
	Table = "proxy_accounts"
)

// Columns holds all SQL columns for proxyaccount fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldUserID,
	FieldNodeID,
	FieldInventoryID,
	FieldProtocol,
	FieldListenIP,
	FieldPort,
	FieldUsername,
	FieldPassword,
	FieldConnectionURI,
	FieldRuntimeEmail,
	FieldEgressLimitBps,
	FieldIngressLimitBps,
	FieldMaxConnections,
	FieldStatus,
	FieldLifecycleStatus,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultConnectionURI holds the default value on creation for the "connection_uri" field.
	DefaultConnectionURI string
	// DefaultEgressLimitBps holds the default value on creation for the "egress_limit_bps" field.
	DefaultEgressLimitBps uint64
	// DefaultIngressLimitBps holds the default value on creation for the "ingress_limit_bps" field.
	DefaultIngressLimitBps uint64
	// DefaultMaxConnections holds the default value on creation for the "max_connections" field.
	DefaultMaxConnections uint32
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProxyAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByInventoryID orders the results by the inventory_id field.
func ByInventoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInventoryID, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByListenIP orders the results by the listen_ip field.
func ByListenIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldListenIP, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByConnectionURI orders the results by the connection_uri field.
func ByConnectionURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionURI, opts...).ToFunc()
}

// ByRuntimeEmail orders the results by the runtime_email field.
func ByRuntimeEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeEmail, opts...).ToFunc()
}

// ByEgressLimitBps orders the results by the egress_limit_bps field.
func ByEgressLimitBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEgressLimitBps, opts...).ToFunc()
}

// ByIngressLimitBps orders the results by the ingress_limit_bps field.
func ByIngressLimitBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIngressLimitBps, opts...).ToFunc()
}

// ByMaxConnections orders the results by the max_connections field.
func ByMaxConnections(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxConnections, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLifecycleStatus orders the results by the lifecycle_status field.
func ByLifecycleStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLifecycleStatus, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
