// Code generated by ent, DO NOT EDIT.

package walletledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContainsFold(FieldID, id))
}

// WalletID applies equality check predicate on the "wallet_id" field. It's identical to WalletIDEQ.
func WalletID(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldWalletID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldUserID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldType, v))
}

// AmountCents applies equality check predicate on the "amount_cents" field. It's identical to AmountCentsEQ.
func AmountCents(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldAmountCents, v))
}

// BalanceAfterCents applies equality check predicate on the "balance_after_cents" field. It's identical to BalanceAfterCentsEQ.
func BalanceAfterCents(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldBalanceAfterCents, v))
}

// HeldAfterCents applies equality check predicate on the "held_after_cents" field. It's identical to HeldAfterCentsEQ.
func HeldAfterCents(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldHeldAfterCents, v))
}

// ReferenceType applies equality check predicate on the "reference_type" field. It's identical to ReferenceTypeEQ.
func ReferenceType(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceID applies equality check predicate on the "reference_id" field. It's identical to ReferenceIDEQ.
func ReferenceID(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldReferenceID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldIdempotencyKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// WalletIDEQ applies the EQ predicate on the "wallet_id" field.
func WalletIDEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldWalletID, v))
}

// WalletIDNEQ applies the NEQ predicate on the "wallet_id" field.
func WalletIDNEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldWalletID, v))
}

// WalletIDIn applies the In predicate on the "wallet_id" field.
func WalletIDIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldWalletID, vs...))
}

// WalletIDNotIn applies the NotIn predicate on the "wallet_id" field.
func WalletIDNotIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldWalletID, vs...))
}

// WalletIDGT applies the GT predicate on the "wallet_id" field.
func WalletIDGT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldWalletID, v))
}

// WalletIDGTE applies the GTE predicate on the "wallet_id" field.
func WalletIDGTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldWalletID, v))
}

// WalletIDLT applies the LT predicate on the "wallet_id" field.
func WalletIDLT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldWalletID, v))
}

// WalletIDLTE applies the LTE predicate on the "wallet_id" field.
func WalletIDLTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldWalletID, v))
}

// WalletIDContains applies the Contains predicate on the "wallet_id" field.
func WalletIDContains(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContains(FieldWalletID, v))
}

// WalletIDHasPrefix applies the HasPrefix predicate on the "wallet_id" field.
func WalletIDHasPrefix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasPrefix(FieldWalletID, v))
}

// WalletIDHasSuffix applies the HasSuffix predicate on the "wallet_id" field.
func WalletIDHasSuffix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasSuffix(FieldWalletID, v))
}

// WalletIDEqualFold applies the EqualFold predicate on the "wallet_id" field.
func WalletIDEqualFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEqualFold(FieldWalletID, v))
}

// WalletIDContainsFold applies the ContainsFold predicate on the "wallet_id" field.
func WalletIDContainsFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContainsFold(FieldWalletID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContainsFold(FieldUserID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContainsFold(FieldType, v))
}

// AmountCentsEQ applies the EQ predicate on the "amount_cents" field.
func AmountCentsEQ(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldAmountCents, v))
}

// AmountCentsNEQ applies the NEQ predicate on the "amount_cents" field.
func AmountCentsNEQ(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldAmountCents, v))
}

// AmountCentsIn applies the In predicate on the "amount_cents" field.
func AmountCentsIn(vs ...int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldAmountCents, vs...))
}

// AmountCentsNotIn applies the NotIn predicate on the "amount_cents" field.
func AmountCentsNotIn(vs ...int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldAmountCents, vs...))
}

// AmountCentsGT applies the GT predicate on the "amount_cents" field.
func AmountCentsGT(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldAmountCents, v))
}

// AmountCentsGTE applies the GTE predicate on the "amount_cents" field.
func AmountCentsGTE(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldAmountCents, v))
}

// AmountCentsLT applies the LT predicate on the "amount_cents" field.
func AmountCentsLT(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldAmountCents, v))
}

// AmountCentsLTE applies the LTE predicate on the "amount_cents" field.
func AmountCentsLTE(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldAmountCents, v))
}

// BalanceAfterCentsEQ applies the EQ predicate on the "balance_after_cents" field.
func BalanceAfterCentsEQ(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldBalanceAfterCents, v))
}

// BalanceAfterCentsNEQ applies the NEQ predicate on the "balance_after_cents" field.
func BalanceAfterCentsNEQ(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldBalanceAfterCents, v))
}

// BalanceAfterCentsIn applies the In predicate on the "balance_after_cents" field.
func BalanceAfterCentsIn(vs ...int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldBalanceAfterCents, vs...))
}

// BalanceAfterCentsNotIn applies the NotIn predicate on the "balance_after_cents" field.
func BalanceAfterCentsNotIn(vs ...int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldBalanceAfterCents, vs...))
}

// BalanceAfterCentsGT applies the GT predicate on the "balance_after_cents" field.
func BalanceAfterCentsGT(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldBalanceAfterCents, v))
}

// BalanceAfterCentsGTE applies the GTE predicate on the "balance_after_cents" field.
func BalanceAfterCentsGTE(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldBalanceAfterCents, v))
}

// BalanceAfterCentsLT applies the LT predicate on the "balance_after_cents" field.
func BalanceAfterCentsLT(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldBalanceAfterCents, v))
}

// BalanceAfterCentsLTE applies the LTE predicate on the "balance_after_cents" field.
func BalanceAfterCentsLTE(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldBalanceAfterCents, v))
}

// HeldAfterCentsEQ applies the EQ predicate on the "held_after_cents" field.
func HeldAfterCentsEQ(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldHeldAfterCents, v))
}

// HeldAfterCentsNEQ applies the NEQ predicate on the "held_after_cents" field.
func HeldAfterCentsNEQ(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldHeldAfterCents, v))
}

// HeldAfterCentsIn applies the In predicate on the "held_after_cents" field.
func HeldAfterCentsIn(vs ...int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldHeldAfterCents, vs...))
}

// HeldAfterCentsNotIn applies the NotIn predicate on the "held_after_cents" field.
func HeldAfterCentsNotIn(vs ...int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldHeldAfterCents, vs...))
}

// HeldAfterCentsGT applies the GT predicate on the "held_after_cents" field.
func HeldAfterCentsGT(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldHeldAfterCents, v))
}

// HeldAfterCentsGTE applies the GTE predicate on the "held_after_cents" field.
func HeldAfterCentsGTE(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldHeldAfterCents, v))
}

// HeldAfterCentsLT applies the LT predicate on the "held_after_cents" field.
func HeldAfterCentsLT(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldHeldAfterCents, v))
}

// HeldAfterCentsLTE applies the LTE predicate on the "held_after_cents" field.
func HeldAfterCentsLTE(v int64) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldHeldAfterCents, v))
}

// ReferenceTypeEQ applies the EQ predicate on the "reference_type" field.
func ReferenceTypeEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceTypeNEQ applies the NEQ predicate on the "reference_type" field.
func ReferenceTypeNEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldReferenceType, v))
}

// ReferenceTypeIn applies the In predicate on the "reference_type" field.
func ReferenceTypeIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldReferenceType, vs...))
}

// ReferenceTypeNotIn applies the NotIn predicate on the "reference_type" field.
func ReferenceTypeNotIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldReferenceType, vs...))
}

// ReferenceTypeGT applies the GT predicate on the "reference_type" field.
func ReferenceTypeGT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldReferenceType, v))
}

// ReferenceTypeGTE applies the GTE predicate on the "reference_type" field.
func ReferenceTypeGTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldReferenceType, v))
}

// ReferenceTypeLT applies the LT predicate on the "reference_type" field.
func ReferenceTypeLT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldReferenceType, v))
}

// ReferenceTypeLTE applies the LTE predicate on the "reference_type" field.
func ReferenceTypeLTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldReferenceType, v))
}

// ReferenceTypeContains applies the Contains predicate on the "reference_type" field.
func ReferenceTypeContains(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContains(FieldReferenceType, v))
}

// ReferenceTypeHasPrefix applies the HasPrefix predicate on the "reference_type" field.
func ReferenceTypeHasPrefix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasPrefix(FieldReferenceType, v))
}

// ReferenceTypeHasSuffix applies the HasSuffix predicate on the "reference_type" field.
func ReferenceTypeHasSuffix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasSuffix(FieldReferenceType, v))
}

// ReferenceTypeEqualFold applies the EqualFold predicate on the "reference_type" field.
func ReferenceTypeEqualFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEqualFold(FieldReferenceType, v))
}

// ReferenceTypeContainsFold applies the ContainsFold predicate on the "reference_type" field.
func ReferenceTypeContainsFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContainsFold(FieldReferenceType, v))
}

// ReferenceIDEQ applies the EQ predicate on the "reference_id" field.
func ReferenceIDEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldReferenceID, v))
}

// ReferenceIDNEQ applies the NEQ predicate on the "reference_id" field.
func ReferenceIDNEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldReferenceID, v))
}

// ReferenceIDIn applies the In predicate on the "reference_id" field.
func ReferenceIDIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldReferenceID, vs...))
}

// ReferenceIDNotIn applies the NotIn predicate on the "reference_id" field.
func ReferenceIDNotIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldReferenceID, vs...))
}

// ReferenceIDGT applies the GT predicate on the "reference_id" field.
func ReferenceIDGT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldReferenceID, v))
}

// ReferenceIDGTE applies the GTE predicate on the "reference_id" field.
func ReferenceIDGTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldReferenceID, v))
}

// ReferenceIDLT applies the LT predicate on the "reference_id" field.
func ReferenceIDLT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldReferenceID, v))
}

// ReferenceIDLTE applies the LTE predicate on the "reference_id" field.
func ReferenceIDLTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldReferenceID, v))
}

// ReferenceIDContains applies the Contains predicate on the "reference_id" field.
func ReferenceIDContains(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContains(FieldReferenceID, v))
}

// ReferenceIDHasPrefix applies the HasPrefix predicate on the "reference_id" field.
func ReferenceIDHasPrefix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasPrefix(FieldReferenceID, v))
}

// ReferenceIDHasSuffix applies the HasSuffix predicate on the "reference_id" field.
func ReferenceIDHasSuffix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasSuffix(FieldReferenceID, v))
}

// ReferenceIDEqualFold applies the EqualFold predicate on the "reference_id" field.
func ReferenceIDEqualFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEqualFold(FieldReferenceID, v))
}

// ReferenceIDContainsFold applies the ContainsFold predicate on the "reference_id" field.
func ReferenceIDContainsFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContainsFold(FieldReferenceID, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WalletLedger {
	return predicate.WalletLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WalletLedger) predicate.WalletLedger {
	return predicate.WalletLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WalletLedger) predicate.WalletLedger {
	return predicate.WalletLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WalletLedger) predicate.WalletLedger {
	return predicate.WalletLedger(sql.NotPredicates(p))
}
