// Code generated by ent, DO NOT EDIT.

package inventoryreservation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContainsFold(FieldID, id))
}

// InventoryID applies equality check predicate on the "inventory_id" field. It's identical to InventoryIDEQ.
func InventoryID(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldInventoryID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldUserID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldOrderID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldUpdatedAt, v))
}

// InventoryIDEQ applies the EQ predicate on the "inventory_id" field.
func InventoryIDEQ(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldInventoryID, v))
}

// InventoryIDNEQ applies the NEQ predicate on the "inventory_id" field.
func InventoryIDNEQ(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNEQ(FieldInventoryID, v))
}

// InventoryIDIn applies the In predicate on the "inventory_id" field.
func InventoryIDIn(vs ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldIn(FieldInventoryID, vs...))
}

// InventoryIDNotIn applies the NotIn predicate on the "inventory_id" field.
func InventoryIDNotIn(vs ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNotIn(FieldInventoryID, vs...))
}

// InventoryIDGT applies the GT predicate on the "inventory_id" field.
func InventoryIDGT(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGT(FieldInventoryID, v))
}

// InventoryIDGTE applies the GTE predicate on the "inventory_id" field.
func InventoryIDGTE(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGTE(FieldInventoryID, v))
}

// InventoryIDLT applies the LT predicate on the "inventory_id" field.
func InventoryIDLT(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLT(FieldInventoryID, v))
}

// InventoryIDLTE applies the LTE predicate on the "inventory_id" field.
func InventoryIDLTE(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLTE(FieldInventoryID, v))
}

// InventoryIDContains applies the Contains predicate on the "inventory_id" field.
func InventoryIDContains(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContains(FieldInventoryID, v))
}

// InventoryIDHasPrefix applies the HasPrefix predicate on the "inventory_id" field.
func InventoryIDHasPrefix(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldHasPrefix(FieldInventoryID, v))
}

// InventoryIDHasSuffix applies the HasSuffix predicate on the "inventory_id" field.
func InventoryIDHasSuffix(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldHasSuffix(FieldInventoryID, v))
}

// InventoryIDEqualFold applies the EqualFold predicate on the "inventory_id" field.
func InventoryIDEqualFold(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEqualFold(FieldInventoryID, v))
}

// InventoryIDContainsFold applies the ContainsFold predicate on the "inventory_id" field.
func InventoryIDContainsFold(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContainsFold(FieldInventoryID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContainsFold(FieldUserID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDContains applies the Contains predicate on the "order_id" field.
func OrderIDContains(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContains(FieldOrderID, v))
}

// OrderIDHasPrefix applies the HasPrefix predicate on the "order_id" field.
func OrderIDHasPrefix(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldHasPrefix(FieldOrderID, v))
}

// OrderIDHasSuffix applies the HasSuffix predicate on the "order_id" field.
func OrderIDHasSuffix(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldHasSuffix(FieldOrderID, v))
}

// OrderIDEqualFold applies the EqualFold predicate on the "order_id" field.
func OrderIDEqualFold(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEqualFold(FieldOrderID, v))
}

// OrderIDContainsFold applies the ContainsFold predicate on the "order_id" field.
func OrderIDContainsFold(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContainsFold(FieldOrderID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InventoryReservation) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InventoryReservation) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InventoryReservation) predicate.InventoryReservation {
	return predicate.InventoryReservation(sql.NotPredicates(p))
}
