// Code generated by ent, DO NOT EDIT.

package line

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/rayip/rayip/services/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Line {
	return predicate.Line(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Line {
	return predicate.Line(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Line {
	return predicate.Line(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Line {
	return predicate.Line(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Line {
	return predicate.Line(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Line {
	return predicate.Line(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Line {
	return predicate.Line(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Line {
	return predicate.Line(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Line {
	return predicate.Line(sql.FieldContainsFold(FieldID, id))
}

// RegionID applies equality check predicate on the "region_id" field. It's identical to RegionIDEQ.
func RegionID(v string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldRegionID, v))
}

// CityID applies equality check predicate on the "city_id" field. It's identical to CityIDEQ.
func CityID(v string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldCityID, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldNodeID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldUpdatedAt, v))
}

// RegionIDEQ applies the EQ predicate on the "region_id" field.
func RegionIDEQ(v string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldRegionID, v))
}

// RegionIDNEQ applies the NEQ predicate on the "region_id" field.
func RegionIDNEQ(v string) predicate.Line {
	return predicate.Line(sql.FieldNEQ(FieldRegionID, v))
}

// RegionIDIn applies the In predicate on the "region_id" field.
func RegionIDIn(vs ...string) predicate.Line {
	return predicate.Line(sql.FieldIn(FieldRegionID, vs...))
}

// RegionIDNotIn applies the NotIn predicate on the "region_id" field.
func RegionIDNotIn(vs ...string) predicate.Line {
	return predicate.Line(sql.FieldNotIn(FieldRegionID, vs...))
}

// RegionIDGT applies the GT predicate on the "region_id" field.
func RegionIDGT(v string) predicate.Line {
	return predicate.Line(sql.FieldGT(FieldRegionID, v))
}

// RegionIDGTE applies the GTE predicate on the "region_id" field.
func RegionIDGTE(v string) predicate.Line {
	return predicate.Line(sql.FieldGTE(FieldRegionID, v))
}

// RegionIDLT applies the LT predicate on the "region_id" field.
func RegionIDLT(v string) predicate.Line {
	return predicate.Line(sql.FieldLT(FieldRegionID, v))
}

// RegionIDLTE applies the LTE predicate on the "region_id" field.
func RegionIDLTE(v string) predicate.Line {
	return predicate.Line(sql.FieldLTE(FieldRegionID, v))
}

// RegionIDContains applies the Contains predicate on the "region_id" field.
func RegionIDContains(v string) predicate.Line {
	return predicate.Line(sql.FieldContains(FieldRegionID, v))
}

// RegionIDHasPrefix applies the HasPrefix predicate on the "region_id" field.
func RegionIDHasPrefix(v string) predicate.Line {
	return predicate.Line(sql.FieldHasPrefix(FieldRegionID, v))
}

// RegionIDHasSuffix applies the HasSuffix predicate on the "region_id" field.
func RegionIDHasSuffix(v string) predicate.Line {
	return predicate.Line(sql.FieldHasSuffix(FieldRegionID, v))
}

// RegionIDEqualFold applies the EqualFold predicate on the "region_id" field.
func RegionIDEqualFold(v string) predicate.Line {
	return predicate.Line(sql.FieldEqualFold(FieldRegionID, v))
}

// RegionIDContainsFold applies the ContainsFold predicate on the "region_id" field.
func RegionIDContainsFold(v string) predicate.Line {
	return predicate.Line(sql.FieldContainsFold(FieldRegionID, v))
}

// CityIDEQ applies the EQ predicate on the "city_id" field.
func CityIDEQ(v string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldCityID, v))
}

// CityIDNEQ applies the NEQ predicate on the "city_id" field.
func CityIDNEQ(v string) predicate.Line {
	return predicate.Line(sql.FieldNEQ(FieldCityID, v))
}

// CityIDIn applies the In predicate on the "city_id" field.
func CityIDIn(vs ...string) predicate.Line {
	return predicate.Line(sql.FieldIn(FieldCityID, vs...))
}

// CityIDNotIn applies the NotIn predicate on the "city_id" field.
func CityIDNotIn(vs ...string) predicate.Line {
	return predicate.Line(sql.FieldNotIn(FieldCityID, vs...))
}

// CityIDGT applies the GT predicate on the "city_id" field.
func CityIDGT(v string) predicate.Line {
	return predicate.Line(sql.FieldGT(FieldCityID, v))
}

// CityIDGTE applies the GTE predicate on the "city_id" field.
func CityIDGTE(v string) predicate.Line {
	return predicate.Line(sql.FieldGTE(FieldCityID, v))
}

// CityIDLT applies the LT predicate on the "city_id" field.
func CityIDLT(v string) predicate.Line {
	return predicate.Line(sql.FieldLT(FieldCityID, v))
}

// CityIDLTE applies the LTE predicate on the "city_id" field.
func CityIDLTE(v string) predicate.Line {
	return predicate.Line(sql.FieldLTE(FieldCityID, v))
}

// CityIDContains applies the Contains predicate on the "city_id" field.
func CityIDContains(v string) predicate.Line {
	return predicate.Line(sql.FieldContains(FieldCityID, v))
}

// CityIDHasPrefix applies the HasPrefix predicate on the "city_id" field.
func CityIDHasPrefix(v string) predicate.Line {
	return predicate.Line(sql.FieldHasPrefix(FieldCityID, v))
}

// CityIDHasSuffix applies the HasSuffix predicate on the "city_id" field.
func CityIDHasSuffix(v string) predicate.Line {
	return predicate.Line(sql.FieldHasSuffix(FieldCityID, v))
}

// CityIDEqualFold applies the EqualFold predicate on the "city_id" field.
func CityIDEqualFold(v string) predicate.Line {
	return predicate.Line(sql.FieldEqualFold(FieldCityID, v))
}

// CityIDContainsFold applies the ContainsFold predicate on the "city_id" field.
func CityIDContainsFold(v string) predicate.Line {
	return predicate.Line(sql.FieldContainsFold(FieldCityID, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.Line {
	return predicate.Line(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.Line {
	return predicate.Line(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.Line {
	return predicate.Line(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.Line {
	return predicate.Line(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.Line {
	return predicate.Line(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.Line {
	return predicate.Line(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.Line {
	return predicate.Line(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.Line {
	return predicate.Line(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.Line {
	return predicate.Line(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.Line {
	return predicate.Line(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.Line {
	return predicate.Line(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.Line {
	return predicate.Line(sql.FieldContainsFold(FieldNodeID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Line {
	return predicate.Line(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Line {
	return predicate.Line(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Line {
	return predicate.Line(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Line {
	return predicate.Line(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Line {
	return predicate.Line(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Line {
	return predicate.Line(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Line {
	return predicate.Line(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Line {
	return predicate.Line(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Line {
	return predicate.Line(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Line {
	return predicate.Line(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Line {
	return predicate.Line(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Line {
	return predicate.Line(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Line {
	return predicate.Line(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Line {
	return predicate.Line(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Line {
	return predicate.Line(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Line {
	return predicate.Line(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Line {
	return predicate.Line(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Line {
	return predicate.Line(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Line) predicate.Line {
	return predicate.Line(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Line) predicate.Line {
	return predicate.Line(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Line) predicate.Line {
	return predicate.Line(sql.NotPredicates(p))
}
