// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/rayip/rayip/services/api/ent"
)

// The AdminUserFunc type is an adapter to allow the use of ordinary
// function as AdminUser mutator.
type AdminUserFunc func(context.Context, *ent.AdminUserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AdminUserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AdminUserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AdminUserMutation", m)
}

// The AuditLogFunc type is an adapter to allow the use of ordinary
// function as AuditLog mutator.
type AuditLogFunc func(context.Context, *ent.AuditLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AuditLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AuditLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AuditLogMutation", m)
}

// The CityFunc type is an adapter to allow the use of ordinary
// function as City mutator.
type CityFunc func(context.Context, *ent.CityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CityMutation", m)
}

// The FulfillmentAttemptFunc type is an adapter to allow the use of ordinary
// function as FulfillmentAttempt mutator.
type FulfillmentAttemptFunc func(context.Context, *ent.FulfillmentAttemptMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FulfillmentAttemptFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FulfillmentAttemptMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FulfillmentAttemptMutation", m)
}

// The FulfillmentJobFunc type is an adapter to allow the use of ordinary
// function as FulfillmentJob mutator.
type FulfillmentJobFunc func(context.Context, *ent.FulfillmentJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FulfillmentJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FulfillmentJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FulfillmentJobMutation", m)
}

// The InventoryReservationFunc type is an adapter to allow the use of ordinary
// function as InventoryReservation mutator.
type InventoryReservationFunc func(context.Context, *ent.InventoryReservationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f InventoryReservationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.InventoryReservationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.InventoryReservationMutation", m)
}

// The LineFunc type is an adapter to allow the use of ordinary
// function as Line mutator.
type LineFunc func(context.Context, *ent.LineMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LineFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LineMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LineMutation", m)
}

// The NodeFunc type is an adapter to allow the use of ordinary
// function as Node mutator.
type NodeFunc func(context.Context, *ent.NodeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NodeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NodeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NodeMutation", m)
}

// The NodeAgentSessionFunc type is an adapter to allow the use of ordinary
// function as NodeAgentSession mutator.
type NodeAgentSessionFunc func(context.Context, *ent.NodeAgentSessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NodeAgentSessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NodeAgentSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NodeAgentSessionMutation", m)
}

// The NodeCapabilitySnapshotFunc type is an adapter to allow the use of ordinary
// function as NodeCapabilitySnapshot mutator.
type NodeCapabilitySnapshotFunc func(context.Context, *ent.NodeCapabilitySnapshotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NodeCapabilitySnapshotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NodeCapabilitySnapshotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NodeCapabilitySnapshotMutation", m)
}

// The NodeInventoryIPFunc type is an adapter to allow the use of ordinary
// function as NodeInventoryIP mutator.
type NodeInventoryIPFunc func(context.Context, *ent.NodeInventoryIPMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NodeInventoryIPFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NodeInventoryIPMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NodeInventoryIPMutation", m)
}

// The NodeJobFunc type is an adapter to allow the use of ordinary
// function as NodeJob mutator.
type NodeJobFunc func(context.Context, *ent.NodeJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NodeJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NodeJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NodeJobMutation", m)
}

// The NodeJobAttemptFunc type is an adapter to allow the use of ordinary
// function as NodeJobAttempt mutator.
type NodeJobAttemptFunc func(context.Context, *ent.NodeJobAttemptMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NodeJobAttemptFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NodeJobAttemptMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NodeJobAttemptMutation", m)
}

// The NodeRuntimeStatusFunc type is an adapter to allow the use of ordinary
// function as NodeRuntimeStatus mutator.
type NodeRuntimeStatusFunc func(context.Context, *ent.NodeRuntimeStatusMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NodeRuntimeStatusFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NodeRuntimeStatusMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NodeRuntimeStatusMutation", m)
}

// The OutboxEventFunc type is an adapter to allow the use of ordinary
// function as OutboxEvent mutator.
type OutboxEventFunc func(context.Context, *ent.OutboxEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OutboxEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OutboxEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OutboxEventMutation", m)
}

// The PaymentOrderFunc type is an adapter to allow the use of ordinary
// function as PaymentOrder mutator.
type PaymentOrderFunc func(context.Context, *ent.PaymentOrderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PaymentOrderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PaymentOrderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PaymentOrderMutation", m)
}

// The ProductFunc type is an adapter to allow the use of ordinary
// function as Product mutator.
type ProductFunc func(context.Context, *ent.ProductMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProductFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProductMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProductMutation", m)
}

// The ProductPriceFunc type is an adapter to allow the use of ordinary
// function as ProductPrice mutator.
type ProductPriceFunc func(context.Context, *ent.ProductPriceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProductPriceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProductPriceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProductPriceMutation", m)
}

// The ProxyAccountFunc type is an adapter to allow the use of ordinary
// function as ProxyAccount mutator.
type ProxyAccountFunc func(context.Context, *ent.ProxyAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProxyAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProxyAccountMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProxyAccountMutation", m)
}

// The ProxyOrderFunc type is an adapter to allow the use of ordinary
// function as ProxyOrder mutator.
type ProxyOrderFunc func(context.Context, *ent.ProxyOrderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProxyOrderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProxyOrderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProxyOrderMutation", m)
}

// The RatePolicyFunc type is an adapter to allow the use of ordinary
// function as RatePolicy mutator.
type RatePolicyFunc func(context.Context, *ent.RatePolicyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RatePolicyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RatePolicyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RatePolicyMutation", m)
}

// The RegionFunc type is an adapter to allow the use of ordinary
// function as Region mutator.
type RegionFunc func(context.Context, *ent.RegionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RegionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RegionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RegionMutation", m)
}

// The RuntimeAccountStateFunc type is an adapter to allow the use of ordinary
// function as RuntimeAccountState mutator.
type RuntimeAccountStateFunc func(context.Context, *ent.RuntimeAccountStateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RuntimeAccountStateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RuntimeAccountStateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RuntimeAccountStateMutation", m)
}

// The RuntimeApplyResultFunc type is an adapter to allow the use of ordinary
// function as RuntimeApplyResult mutator.
type RuntimeApplyResultFunc func(context.Context, *ent.RuntimeApplyResultMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RuntimeApplyResultFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RuntimeApplyResultMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RuntimeApplyResultMutation", m)
}

// The RuntimeChangeLogFunc type is an adapter to allow the use of ordinary
// function as RuntimeChangeLog mutator.
type RuntimeChangeLogFunc func(context.Context, *ent.RuntimeChangeLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RuntimeChangeLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RuntimeChangeLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RuntimeChangeLogMutation", m)
}

// The RuntimeLabAccountFunc type is an adapter to allow the use of ordinary
// function as RuntimeLabAccount mutator.
type RuntimeLabAccountFunc func(context.Context, *ent.RuntimeLabAccountMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RuntimeLabAccountFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RuntimeLabAccountMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RuntimeLabAccountMutation", m)
}

// The SessionFunc type is an adapter to allow the use of ordinary
// function as Session mutator.
type SessionFunc func(context.Context, *ent.SessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SessionMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// The WalletFunc type is an adapter to allow the use of ordinary
// function as Wallet mutator.
type WalletFunc func(context.Context, *ent.WalletMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WalletFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WalletMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WalletMutation", m)
}

// The WalletHoldFunc type is an adapter to allow the use of ordinary
// function as WalletHold mutator.
type WalletHoldFunc func(context.Context, *ent.WalletHoldMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WalletHoldFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WalletHoldMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WalletHoldMutation", m)
}

// The WalletLedgerFunc type is an adapter to allow the use of ordinary
// function as WalletLedger mutator.
type WalletLedgerFunc func(context.Context, *ent.WalletLedgerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WalletLedgerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WalletLedgerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WalletLedgerMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
