// Code generated by ent, DO NOT EDIT.

package nodeinventoryip

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the nodeinventoryip type in the database.
	Label = "node_inventory_ip"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLineID holds the string denoting the line_id field in the database.
	FieldLineID = "line_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldProtocols holds the string denoting the protocols field in the database.
	FieldProtocols = "protocols"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldManualHold holds the string denoting the manual_hold field in the database.
	FieldManualHold = "manual_hold"
	// FieldComplianceHold holds the string denoting the compliance_hold field in the database.
	FieldComplianceHold = "compliance_hold"
	// FieldSoldOrderID holds the string denoting the sold_order_id field in the database.
	FieldSoldOrderID = "sold_order_id"
	// FieldReservedOrderID holds the string denoting the reserved_order_id field in the database.
	FieldReservedOrderID = "reserved_order_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the nodeinventoryip in the database.
	Table = "node_inventory_ips"
)

// Columns holds all SQL columns for nodeinventoryip fields.
var Columns = []string{
	FieldID,
	FieldLineID,
	FieldNodeID,
	FieldIP,
	FieldPort,
	FieldProtocols,
	FieldStatus,
	FieldManualHold,
	FieldComplianceHold,
	FieldSoldOrderID,
	FieldReservedOrderID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProtocols holds the default value on creation for the "protocols" field.
	DefaultProtocols []string
	// DefaultManualHold holds the default value on creation for the "manual_hold" field.
	DefaultManualHold bool
	// DefaultComplianceHold holds the default value on creation for the "compliance_hold" field.
	DefaultComplianceHold bool
	// DefaultSoldOrderID holds the default value on creation for the "sold_order_id" field.
	DefaultSoldOrderID string
	// DefaultReservedOrderID holds the default value on creation for the "reserved_order_id" field.
	DefaultReservedOrderID string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the NodeInventoryIP queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLineID orders the results by the line_id field.
func ByLineID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLineID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByManualHold orders the results by the manual_hold field.
func ByManualHold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualHold, opts...).ToFunc()
}

// ByComplianceHold orders the results by the compliance_hold field.
func ByComplianceHold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComplianceHold, opts...).ToFunc()
}

// BySoldOrderID orders the results by the sold_order_id field.
func BySoldOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSoldOrderID, opts...).ToFunc()
}

// ByReservedOrderID orders the results by the reserved_order_id field.
func ByReservedOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedOrderID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
