// Code generated by ent, DO NOT EDIT.

package proxyorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the proxyorder type in the database.
	Label = "proxy_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldInventoryID holds the string denoting the inventory_id field in the database.
	FieldInventoryID = "inventory_id"
	// FieldReservationID holds the string denoting the reservation_id field in the database.
	FieldReservationID = "reservation_id"
	// FieldWalletHoldID holds the string denoting the wallet_hold_id field in the database.
	FieldWalletHoldID = "wallet_hold_id"
	// FieldProxyAccountID holds the string denoting the proxy_account_id field in the database.
	FieldProxyAccountID = "proxy_account_id"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldDurationDays holds the string denoting the duration_days field in the database.
	FieldDurationDays = "duration_days"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldAmountCents holds the string denoting the amount_cents field in the database.
	FieldAmountCents = "amount_cents"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFailureReason holds the string denoting the failure_reason field in the database.
	FieldFailureReason = "failure_reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeliveredAt holds the string denoting the delivered_at field in the database.
	FieldDeliveredAt = "delivered_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the proxyorder in the database.
	Table = "proxy_orders"
)

// Columns holds all SQL columns for proxyorder fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldProductID,
	FieldInventoryID,
	FieldReservationID,
	FieldWalletHoldID,
	FieldProxyAccountID,
	FieldIdempotencyKey,
	FieldProtocol,
	FieldDurationDays,
	FieldQuantity,
	FieldAmountCents,
	FieldStatus,
	FieldFailureReason,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeliveredAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReservationID holds the default value on creation for the "reservation_id" field.
	DefaultReservationID string
	// DefaultWalletHoldID holds the default value on creation for the "wallet_hold_id" field.
	DefaultWalletHoldID string
	// DefaultProxyAccountID holds the default value on creation for the "proxy_account_id" field.
	DefaultProxyAccountID string
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int
	// DefaultFailureReason holds the default value on creation for the "failure_reason" field.
	DefaultFailureReason string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProxyOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByInventoryID orders the results by the inventory_id field.
func ByInventoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInventoryID, opts...).ToFunc()
}

// ByReservationID orders the results by the reservation_id field.
func ByReservationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationID, opts...).ToFunc()
}

// ByWalletHoldID orders the results by the wallet_hold_id field.
func ByWalletHoldID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletHoldID, opts...).ToFunc()
}

// ByProxyAccountID orders the results by the proxy_account_id field.
func ByProxyAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyAccountID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByDurationDays orders the results by the duration_days field.
func ByDurationDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationDays, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByAmountCents orders the results by the amount_cents field.
func ByAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCents, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFailureReason orders the results by the failure_reason field.
func ByFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeliveredAt orders the results by the delivered_at field.
func ByDeliveredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveredAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
